import postgres from 'postgres';
const sql = postgres('postgresql://postgres:HVXvedDhYN2kyoI8@db.ozthzccqudrudicnneuu.supabase.co:5432/postgres',{ssl:{rejectUnauthorized:false},max:1});
const r = await sql`SELECT COUNT(*) as cnt FROM sales_orders WHERE order_number LIKE 'HIST-%'`;
const b = await sql`SELECT COUNT(*) as cnt FROM sales_order_items soi JOIN sales_orders so ON so.id=soi.order_id WHERE so.order_number LIKE 'HIST-%'`;
const total = await sql`SELECT COALESCE(SUM(total_amount),0) as t FROM sales_orders WHERE order_number LIKE 'HIST-%'`;
console.log('فواتير محقونة : ' + parseInt(r[0].cnt).toLocaleString() + ' / 7,627');
console.log('بنود محقونة   : ' + parseInt(b[0].cnt).toLocaleString() + ' / 17,058');
console.log('نسبة الاكتمال : ' + (r[0].cnt/7627*100).toFixed(1) + '%');
console.log('إجمالي مسجل  : ' + parseFloat(total[0].t).toLocaleString('en', {minimumFractionDigits:2}) + ' جنيه');
await sql.end();
