/**
 * resequence_customers.mjs
 * =========================
 * إعادة ترقيم العملاء الذين حصلوا على أكواد تلقائية ≥ CUS-01861
 * ليبدأوا من بعد آخر كود أصلي مباشرة (CUS-01658 فصاعداً)
 * ثم ضبط الـ sequence على الكود الأعلى الفعلي
 */
import postgres from 'postgres';

const sql = postgres(
  'postgresql://postgres:HVXvedDhYN2kyoI8@db.ozthzccqudrudicnneuu.supabase.co:5432/postgres',
  { ssl: { rejectUnauthorized: false }, max: 1 }
);

// ── 1. تحليل الوضع الحالي ────────────────────────────────────────
console.log('▶ تحليل الوضع الحالي...\n');

const allCodes = await sql`
  SELECT id, code,
    CAST(substring(code FROM 5) AS int) as num
  FROM customers
  WHERE code ~ '^CUS-[0-9]{5}$'
  ORDER BY num
`;

const maxOriginal = 1657;  // آخر كود أصلي من Excel
const autoGenerated = allCodes.filter(r => r.num > 1860);
const gap = allCodes.filter(r => r.num > maxOriginal && r.num <= 1860);

console.log(`الأكواد الأصلية (≤ CUS-01657): ${allCodes.filter(r => r.num <= maxOriginal).length}`);
console.log(`فجوة غير مستخدمة (01658-01860): ${gap.length} كود — لا يوجد عميل فيها ✓`);
console.log(`أكواد تلقائية (> 01860): ${autoGenerated.length}`);
console.log(`  المدى: CUS-${String(autoGenerated[0]?.num).padStart(5,'0')} → CUS-${String(autoGenerated.at(-1)?.num).padStart(5,'0')}`);

// ── 2. إعادة الترقيم ────────────────────────────────────────────
console.log('\n▶ إعادة الترقيم...');
// نرقّم العملاء التلقائيين من 01658 فصاعداً بالترتيب (created_at)
const autoSorted = await sql`
  SELECT id, code,
    CAST(substring(code FROM 5) AS int) as num
  FROM customers
  WHERE code ~ '^CUS-[0-9]+$'
    AND CAST(substring(code FROM 5) AS int) > 1860
  ORDER BY created_at ASC, id ASC
`;

let counter = maxOriginal + 1;  // يبدأ من 1658

await sql.begin(async tx => {
  for (const row of autoSorted) {
    const newCode = `CUS-${String(counter).padStart(5, '0')}`;
    await tx`
      UPDATE customers SET code = ${newCode}, updated_at = now()
      WHERE id = ${row.id}
    `;
    process.stdout.write(`\r  ${row.code} → ${newCode}  `);
    counter++;
  }
});

const newMax = counter - 1;  // آخر كود استُخدم

// ── 3. ضبط الـ sequence على الكود الأعلى الفعلي ───────────────────
await sql`SELECT setval('customer_code_seq', ${newMax})`;
console.log(`\n\n✓ الـ sequence ضُبطت على ${newMax}`);
console.log(`  الكود التالي: CUS-${String(newMax + 1).padStart(5,'0')}`);

// ── 4. تحقق نهائي ────────────────────────────────────────────────
const verify = await sql`
  SELECT
    COUNT(*)                                                   as total,
    MIN(CAST(substring(code FROM 5) AS int))                   as min_num,
    MAX(CAST(substring(code FROM 5) AS int))                   as max_num,
    COUNT(*) FILTER (WHERE CAST(substring(code FROM 5) AS int)
                          BETWEEN 1658 AND 1860)               as was_gap
  FROM customers
  WHERE code ~ '^CUS-[0-9]{5}$'
`;
const v = verify[0];

console.log('\n📊 التحقق النهائي:');
console.log(`  إجمالي CUS-XXXXX : ${v.total}`);
console.log(`  أقل كود           : CUS-${String(v.min_num).padStart(5,'0')}`);
console.log(`  أعلى كود          : CUS-${String(v.max_num).padStart(5,'0')}`);
console.log(`  عملاء في النطاق   : ${v.was_gap} (كان فارغاً — الآن ممتلئ ✅)`);

const seqVal = await sql`SELECT last_value FROM customer_code_seq`;
console.log(`  sequence           : ${seqVal[0].last_value}`);
console.log(`  تطابق مع max_num  : ${seqVal[0].last_value == v.max_num ? '✅ نعم' : '⚠️ لا'}`);

console.log('\n' + '═'.repeat(55));
console.log(`✅ الترقيم متسلسل تماماً من CUS-00001 إلى CUS-${String(v.max_num).padStart(5,'0')}`);
console.log(`   الكود التالي للعميل الجديد: CUS-${String(parseInt(v.max_num)+1).padStart(5,'0')}`);
console.log('═'.repeat(55));

await sql.end();
