-- ==============================================================
-- 66_rls_initplan_safe.sql
-- GENERATED by 02_generate_rls_migration.js
-- Source: pg_policies catalog (live database snapshot)
-- Generated: 2026-04-04T15:58:16.252Z
--
-- Transformations:
--   auth.uid()                         -> (SELECT auth.uid())
--   check_permission(auth.uid(), X)    -> (SELECT check_permission((SELECT auth.uid()), X))
--   Added TO authenticated on applicable policies
--
-- Stats:
--   Transformed: 258
--   Unchanged:   2
--   Skipped:     1
-- ==============================================================

BEGIN;

-- +++ activities ────────────────────────────────────────
DROP POLICY IF EXISTS "acts_insert" ON activities;
CREATE POLICY "acts_insert" ON activities FOR INSERT
WITH CHECK (((employee_id IN ( SELECT hr_employees.id
   FROM hr_employees
  WHERE (hr_employees.user_id = (SELECT auth.uid())))) AND (created_by = (SELECT auth.uid())) AND (SELECT check_permission((SELECT auth.uid()), 'activities.create'::text))));

DROP POLICY IF EXISTS "acts_read" ON activities;
CREATE POLICY "acts_read" ON activities FOR SELECT
USING (((employee_id IN ( SELECT hr_employees.id
   FROM hr_employees
  WHERE (hr_employees.user_id = (SELECT auth.uid())))) OR ((SELECT check_permission((SELECT auth.uid()), 'activities.read_team'::text)) AND (employee_id IN ( SELECT hr_employees.id
   FROM hr_employees
  WHERE (hr_employees.branch_id = ( SELECT hr_employees_1.branch_id
           FROM hr_employees hr_employees_1
          WHERE (hr_employees_1.user_id = (SELECT auth.uid()))
         LIMIT 1))))) OR (SELECT check_permission((SELECT auth.uid()), 'activities.read_all'::text))));

DROP POLICY IF EXISTS "acts_update" ON activities;
CREATE POLICY "acts_update" ON activities FOR UPDATE
USING ((((employee_id IN ( SELECT hr_employees.id
   FROM hr_employees
  WHERE (hr_employees.user_id = (SELECT auth.uid())))) AND (SELECT check_permission((SELECT auth.uid()), 'activities.update_own'::text)) AND (created_at > (now() - '24:00:00'::interval))) OR (SELECT check_permission((SELECT auth.uid()), 'activities.read_all'::text))));


-- +++ activity_types ────────────────────────────────────
DROP POLICY IF EXISTS "act_types_read" ON activity_types;
CREATE POLICY "act_types_read" ON activity_types FOR SELECT
USING (((SELECT auth.uid()) IS NOT NULL));

DROP POLICY IF EXISTS "act_types_write" ON activity_types;
CREATE POLICY "act_types_write" ON activity_types FOR ALL
USING ((SELECT check_permission((SELECT auth.uid()), 'settings.update'::text)));

DROP POLICY IF EXISTS "activity_types_read" ON activity_types;
CREATE POLICY "activity_types_read" ON activity_types FOR SELECT
USING (((SELECT auth.uid()) IS NOT NULL));


-- +++ approval_rules ────────────────────────────────────
DROP POLICY IF EXISTS "approval_rules_read" ON approval_rules;
CREATE POLICY "approval_rules_read" ON approval_rules FOR SELECT
USING (((SELECT auth.uid()) IS NOT NULL));

DROP POLICY IF EXISTS "approval_rules_write" ON approval_rules;
CREATE POLICY "approval_rules_write" ON approval_rules FOR ALL
USING ((SELECT check_permission((SELECT auth.uid()), 'settings.update'::text)));


-- +++ areas ─────────────────────────────────────────────
DROP POLICY IF EXISTS "areas_read" ON areas;
CREATE POLICY "areas_read" ON areas FOR SELECT
USING (((SELECT auth.uid()) IS NOT NULL));

DROP POLICY IF EXISTS "areas_write" ON areas;
CREATE POLICY "areas_write" ON areas FOR ALL
USING ((SELECT check_permission((SELECT auth.uid()), 'branches.create'::text)));


-- +++ audit_logs ────────────────────────────────────────
DROP POLICY IF EXISTS "audit_insert" ON audit_logs;
CREATE POLICY "audit_insert" ON audit_logs FOR INSERT
WITH CHECK (((SELECT auth.uid()) IS NOT NULL));

DROP POLICY IF EXISTS "audit_select" ON audit_logs;
CREATE POLICY "audit_select" ON audit_logs FOR SELECT
USING (((user_id = (SELECT auth.uid())) OR (SELECT check_permission((SELECT auth.uid()), 'settings.audit.read'::text))));


-- +++ branches ──────────────────────────────────────────
DROP POLICY IF EXISTS "branches_read" ON branches;
CREATE POLICY "branches_read" ON branches FOR SELECT
USING ((SELECT check_permission((SELECT auth.uid()), 'branches.read'::text)));

DROP POLICY IF EXISTS "branches_write" ON branches;
CREATE POLICY "branches_write" ON branches FOR ALL
USING ((SELECT check_permission((SELECT auth.uid()), 'branches.create'::text)));


-- +++ brands ────────────────────────────────────────────
DROP POLICY IF EXISTS "brands_read" ON brands;
CREATE POLICY "brands_read" ON brands FOR SELECT
USING ((SELECT check_permission((SELECT auth.uid()), 'products.read'::text)));

DROP POLICY IF EXISTS "brands_write" ON brands;
CREATE POLICY "brands_write" ON brands FOR ALL
USING ((SELECT check_permission((SELECT auth.uid()), 'products.create'::text)));


-- +++ call_details ──────────────────────────────────────
DROP POLICY IF EXISTS "cd_insert" ON call_details;
CREATE POLICY "cd_insert" ON call_details FOR INSERT
WITH CHECK ((EXISTS ( SELECT 1
   FROM activities a
  WHERE ((a.id = call_details.activity_id) AND (a.employee_id IN ( SELECT hr_employees.id
           FROM hr_employees
          WHERE (hr_employees.user_id = (SELECT auth.uid())))) AND (SELECT check_permission((SELECT auth.uid()), 'activities.create'::text))))));

DROP POLICY IF EXISTS "cd_read" ON call_details;
CREATE POLICY "cd_read" ON call_details FOR SELECT
USING ((EXISTS ( SELECT 1
   FROM activities a
  WHERE ((a.id = call_details.activity_id) AND ((a.employee_id IN ( SELECT hr_employees.id
           FROM hr_employees
          WHERE (hr_employees.user_id = (SELECT auth.uid())))) OR ((SELECT check_permission((SELECT auth.uid()), 'activities.read_team'::text)) AND (a.employee_id IN ( SELECT hr_employees.id
           FROM hr_employees
          WHERE (hr_employees.branch_id = ( SELECT hr_employees_1.branch_id
                   FROM hr_employees hr_employees_1
                  WHERE (hr_employees_1.user_id = (SELECT auth.uid()))))))) OR (SELECT check_permission((SELECT auth.uid()), 'activities.read_all'::text)))))));

DROP POLICY IF EXISTS "cd_rls" ON call_details;
CREATE POLICY "cd_rls" ON call_details FOR ALL
USING ((activity_id IN ( SELECT activities.id
   FROM activities
  WHERE ((activities.employee_id IN ( SELECT hr_employees.id
           FROM hr_employees
          WHERE (hr_employees.user_id = (SELECT auth.uid())))) OR (SELECT check_permission((SELECT auth.uid()), 'activities.read_all'::text))))));

DROP POLICY IF EXISTS "cd_update" ON call_details;
CREATE POLICY "cd_update" ON call_details FOR UPDATE
USING ((EXISTS ( SELECT 1
   FROM activities a
  WHERE ((a.id = call_details.activity_id) AND (((a.employee_id IN ( SELECT hr_employees.id
           FROM hr_employees
          WHERE (hr_employees.user_id = (SELECT auth.uid())))) AND (SELECT check_permission((SELECT auth.uid()), 'activities.update_own'::text))) OR (SELECT check_permission((SELECT auth.uid()), 'activities.read_all'::text)))))))
WITH CHECK ((EXISTS ( SELECT 1
   FROM activities a
  WHERE ((a.id = call_details.activity_id) AND (((a.employee_id IN ( SELECT hr_employees.id
           FROM hr_employees
          WHERE (hr_employees.user_id = (SELECT auth.uid())))) AND (SELECT check_permission((SELECT auth.uid()), 'activities.update_own'::text))) OR (SELECT check_permission((SELECT auth.uid()), 'activities.read_all'::text)))))));


-- +++ call_plan_items ───────────────────────────────────
DROP POLICY IF EXISTS "cpi_delete" ON call_plan_items;
CREATE POLICY "cpi_delete" ON call_plan_items FOR DELETE
USING ((((SELECT check_permission((SELECT auth.uid()), 'call_plans.create'::text)) AND (EXISTS ( SELECT 1
   FROM call_plans cp
  WHERE ((cp.id = call_plan_items.plan_id) AND (cp.employee_id IN ( SELECT hr_employees.id
           FROM hr_employees
          WHERE (hr_employees.user_id = (SELECT auth.uid())))))))) OR (SELECT check_permission((SELECT auth.uid()), 'call_plans.read_all'::text))));

DROP POLICY IF EXISTS "cpi_insert" ON call_plan_items;
CREATE POLICY "cpi_insert" ON call_plan_items FOR INSERT
WITH CHECK ((((SELECT check_permission((SELECT auth.uid()), 'call_plans.create'::text)) AND (EXISTS ( SELECT 1
   FROM call_plans cp
  WHERE ((cp.id = call_plan_items.plan_id) AND ((cp.employee_id IN ( SELECT hr_employees.id
           FROM hr_employees
          WHERE (hr_employees.user_id = (SELECT auth.uid())))) OR (SELECT check_permission((SELECT auth.uid()), 'call_plans.read_team'::text))))))) OR (SELECT check_permission((SELECT auth.uid()), 'call_plans.read_all'::text))));

DROP POLICY IF EXISTS "cpi_read" ON call_plan_items;
CREATE POLICY "cpi_read" ON call_plan_items FOR SELECT
USING ((EXISTS ( SELECT 1
   FROM call_plans cp
  WHERE ((cp.id = call_plan_items.plan_id) AND ((cp.employee_id IN ( SELECT hr_employees.id
           FROM hr_employees
          WHERE (hr_employees.user_id = (SELECT auth.uid())))) OR (SELECT check_permission((SELECT auth.uid()), 'call_plans.read_all'::text)))))));

DROP POLICY IF EXISTS "cpi_update" ON call_plan_items;
CREATE POLICY "cpi_update" ON call_plan_items FOR UPDATE
USING ((((SELECT check_permission((SELECT auth.uid()), 'activities.create'::text)) AND (EXISTS ( SELECT 1
   FROM call_plans cp
  WHERE ((cp.id = call_plan_items.plan_id) AND (cp.employee_id IN ( SELECT hr_employees.id
           FROM hr_employees
          WHERE (hr_employees.user_id = (SELECT auth.uid())))))))) OR ((SELECT check_permission((SELECT auth.uid()), 'call_plans.create'::text)) AND (EXISTS ( SELECT 1
   FROM call_plans cp
  WHERE ((cp.id = call_plan_items.plan_id) AND (cp.employee_id IN ( SELECT hr_employees.id
           FROM hr_employees
          WHERE (hr_employees.user_id = (SELECT auth.uid())))))))) OR ((SELECT check_permission((SELECT auth.uid()), 'call_plans.confirm'::text)) AND (EXISTS ( SELECT 1
   FROM call_plans cp
  WHERE ((cp.id = call_plan_items.plan_id) AND (cp.employee_id IN ( SELECT hr_employees.id
           FROM hr_employees
          WHERE (hr_employees.branch_id = ( SELECT hr_employees_1.branch_id
                   FROM hr_employees hr_employees_1
                  WHERE (hr_employees_1.user_id = (SELECT auth.uid()))
                 LIMIT 1)))))))) OR (SELECT check_permission((SELECT auth.uid()), 'call_plans.read_all'::text))));


-- +++ call_plan_templates ───────────────────────────────
DROP POLICY IF EXISTS "cpt_insert" ON call_plan_templates;
CREATE POLICY "cpt_insert" ON call_plan_templates FOR INSERT
WITH CHECK (((SELECT check_permission((SELECT auth.uid()), 'call_plans.create'::text)) AND ((branch_id IS NULL) OR (branch_id IN ( SELECT hr_employees.branch_id
   FROM hr_employees
  WHERE (hr_employees.user_id = (SELECT auth.uid())))) OR (SELECT check_permission((SELECT auth.uid()), 'call_plans.read_all'::text)))));

DROP POLICY IF EXISTS "cpt_read" ON call_plan_templates;
CREATE POLICY "cpt_read" ON call_plan_templates FOR SELECT
USING (((SELECT auth.uid()) IS NOT NULL));

DROP POLICY IF EXISTS "cpt_update" ON call_plan_templates;
CREATE POLICY "cpt_update" ON call_plan_templates FOR UPDATE
USING ((((SELECT check_permission((SELECT auth.uid()), 'call_plans.create'::text)) AND ((created_by = (SELECT auth.uid())) OR (employee_id IN ( SELECT hr_employees.id
   FROM hr_employees
  WHERE (hr_employees.branch_id = ( SELECT hr_employees_1.branch_id
           FROM hr_employees hr_employees_1
          WHERE (hr_employees_1.user_id = (SELECT auth.uid())))))) OR (branch_id IN ( SELECT hr_employees.branch_id
   FROM hr_employees
  WHERE (hr_employees.user_id = (SELECT auth.uid())))))) OR (SELECT check_permission((SELECT auth.uid()), 'call_plans.read_all'::text))))
WITH CHECK ((((SELECT check_permission((SELECT auth.uid()), 'call_plans.create'::text)) AND ((created_by = (SELECT auth.uid())) OR (employee_id IN ( SELECT hr_employees.id
   FROM hr_employees
  WHERE (hr_employees.branch_id = ( SELECT hr_employees_1.branch_id
           FROM hr_employees hr_employees_1
          WHERE (hr_employees_1.user_id = (SELECT auth.uid())))))) OR (branch_id IN ( SELECT hr_employees.branch_id
   FROM hr_employees
  WHERE (hr_employees.user_id = (SELECT auth.uid())))))) OR (SELECT check_permission((SELECT auth.uid()), 'call_plans.read_all'::text))));

DROP POLICY IF EXISTS "cpt_write" ON call_plan_templates;
CREATE POLICY "cpt_write" ON call_plan_templates FOR ALL
USING ((SELECT check_permission((SELECT auth.uid()), 'call_plans.create'::text)));


-- +++ call_plans ────────────────────────────────────────
DROP POLICY IF EXISTS "cp_insert" ON call_plans;
CREATE POLICY "cp_insert" ON call_plans FOR INSERT
WITH CHECK (((SELECT check_permission((SELECT auth.uid()), 'call_plans.create'::text)) AND ((employee_id IN ( SELECT hr_employees.id
   FROM hr_employees
  WHERE (hr_employees.user_id = (SELECT auth.uid())))) OR ((SELECT check_permission((SELECT auth.uid()), 'call_plans.read_team'::text)) AND (employee_id IN ( SELECT hr_employees.id
   FROM hr_employees
  WHERE (hr_employees.branch_id = ( SELECT hr_employees_1.branch_id
           FROM hr_employees hr_employees_1
          WHERE (hr_employees_1.user_id = (SELECT auth.uid()))))))) OR (SELECT check_permission((SELECT auth.uid()), 'call_plans.read_all'::text)))));

DROP POLICY IF EXISTS "cp_read" ON call_plans;
CREATE POLICY "cp_read" ON call_plans FOR SELECT
USING (((employee_id IN ( SELECT hr_employees.id
   FROM hr_employees
  WHERE (hr_employees.user_id = (SELECT auth.uid())))) OR ((SELECT check_permission((SELECT auth.uid()), 'call_plans.read_team'::text)) AND (employee_id IN ( SELECT hr_employees.id
   FROM hr_employees
  WHERE (hr_employees.branch_id = ( SELECT hr_employees_1.branch_id
           FROM hr_employees hr_employees_1
          WHERE (hr_employees_1.user_id = (SELECT auth.uid()))
         LIMIT 1))))) OR (SELECT check_permission((SELECT auth.uid()), 'call_plans.read_all'::text))));

DROP POLICY IF EXISTS "cp_update" ON call_plans;
CREATE POLICY "cp_update" ON call_plans FOR UPDATE
USING ((((SELECT check_permission((SELECT auth.uid()), 'call_plans.create'::text)) AND (employee_id IN ( SELECT hr_employees.id
   FROM hr_employees
  WHERE (hr_employees.branch_id = ( SELECT hr_employees_1.branch_id
           FROM hr_employees hr_employees_1
          WHERE (hr_employees_1.user_id = (SELECT auth.uid()))))))) OR ((SELECT check_permission((SELECT auth.uid()), 'call_plans.confirm'::text)) AND (employee_id IN ( SELECT hr_employees.id
   FROM hr_employees
  WHERE (hr_employees.branch_id = ( SELECT hr_employees_1.branch_id
           FROM hr_employees hr_employees_1
          WHERE (hr_employees_1.user_id = (SELECT auth.uid()))))))) OR ((SELECT check_permission((SELECT auth.uid()), 'call_plans.cancel'::text)) AND (employee_id IN ( SELECT hr_employees.id
   FROM hr_employees
  WHERE (hr_employees.branch_id = ( SELECT hr_employees_1.branch_id
           FROM hr_employees hr_employees_1
          WHERE (hr_employees_1.user_id = (SELECT auth.uid()))))))) OR (SELECT check_permission((SELECT auth.uid()), 'call_plans.read_all'::text))))
WITH CHECK ((((SELECT check_permission((SELECT auth.uid()), 'call_plans.create'::text)) AND (employee_id IN ( SELECT hr_employees.id
   FROM hr_employees
  WHERE (hr_employees.branch_id = ( SELECT hr_employees_1.branch_id
           FROM hr_employees hr_employees_1
          WHERE (hr_employees_1.user_id = (SELECT auth.uid()))))))) OR ((SELECT check_permission((SELECT auth.uid()), 'call_plans.confirm'::text)) AND (employee_id IN ( SELECT hr_employees.id
   FROM hr_employees
  WHERE (hr_employees.branch_id = ( SELECT hr_employees_1.branch_id
           FROM hr_employees hr_employees_1
          WHERE (hr_employees_1.user_id = (SELECT auth.uid()))))))) OR ((SELECT check_permission((SELECT auth.uid()), 'call_plans.cancel'::text)) AND (employee_id IN ( SELECT hr_employees.id
   FROM hr_employees
  WHERE (hr_employees.branch_id = ( SELECT hr_employees_1.branch_id
           FROM hr_employees hr_employees_1
          WHERE (hr_employees_1.user_id = (SELECT auth.uid()))))))) OR (SELECT check_permission((SELECT auth.uid()), 'call_plans.read_all'::text))));

DROP POLICY IF EXISTS "cp_write" ON call_plans;
CREATE POLICY "cp_write" ON call_plans FOR ALL
USING ((SELECT check_permission((SELECT auth.uid()), 'call_plans.create'::text)));


-- +++ chart_of_accounts ─────────────────────────────────
DROP POLICY IF EXISTS "coa_read" ON chart_of_accounts;
CREATE POLICY "coa_read" ON chart_of_accounts FOR SELECT
USING (((SELECT auth.uid()) IS NOT NULL));

DROP POLICY IF EXISTS "coa_write" ON chart_of_accounts;
CREATE POLICY "coa_write" ON chart_of_accounts FOR ALL
USING ((SELECT check_permission((SELECT auth.uid()), 'finance.journal.create'::text)));


-- +++ cities ────────────────────────────────────────────
DROP POLICY IF EXISTS "cities_read" ON cities;
CREATE POLICY "cities_read" ON cities FOR SELECT
USING (((SELECT auth.uid()) IS NOT NULL));


-- +++ company_settings ──────────────────────────────────
DROP POLICY IF EXISTS "settings_select" ON company_settings;
CREATE POLICY "settings_select" ON company_settings FOR SELECT
USING (((is_public = true) OR (SELECT check_permission((SELECT auth.uid()), 'settings.read'::text))));

DROP POLICY IF EXISTS "settings_update" ON company_settings;
CREATE POLICY "settings_update" ON company_settings FOR UPDATE
USING ((SELECT check_permission((SELECT auth.uid()), 'settings.update'::text)));


-- +++ custody_accounts ──────────────────────────────────
DROP POLICY IF EXISTS "custody_read" ON custody_accounts;
CREATE POLICY "custody_read" ON custody_accounts FOR SELECT
USING (((employee_id = (SELECT auth.uid())) OR (SELECT check_permission((SELECT auth.uid()), 'finance.custody.read_all'::text))));

DROP POLICY IF EXISTS "custody_write" ON custody_accounts;
CREATE POLICY "custody_write" ON custody_accounts FOR ALL
USING ((SELECT check_permission((SELECT auth.uid()), 'finance.custody.create'::text)));


-- +++ custody_transactions ──────────────────────────────
DROP POLICY IF EXISTS "custody_txn_read" ON custody_transactions;
CREATE POLICY "custody_txn_read" ON custody_transactions FOR SELECT
USING (((SELECT check_permission((SELECT auth.uid()), 'finance.custody.read_all'::text)) OR (custody_id IN ( SELECT custody_accounts.id
   FROM custody_accounts
  WHERE (custody_accounts.employee_id = (SELECT auth.uid()))))));

DROP POLICY IF EXISTS "custody_txn_write" ON custody_transactions;
CREATE POLICY "custody_txn_write" ON custody_transactions FOR ALL
USING ((SELECT check_permission((SELECT auth.uid()), 'finance.custody.transact'::text)));


-- +++ customer_branches ─────────────────────────────────
DROP POLICY IF EXISTS "customer_branches_delete" ON customer_branches;
CREATE POLICY "customer_branches_delete" ON customer_branches FOR DELETE
USING ((SELECT check_permission((SELECT auth.uid()), 'customers.update'::text)));

DROP POLICY IF EXISTS "customer_branches_insert" ON customer_branches;
CREATE POLICY "customer_branches_insert" ON customer_branches FOR INSERT
WITH CHECK (((SELECT check_permission((SELECT auth.uid()), 'customers.create'::text)) OR (SELECT check_permission((SELECT auth.uid()), 'customers.update'::text))));

DROP POLICY IF EXISTS "customer_branches_modify" ON customer_branches;
CREATE POLICY "customer_branches_modify" ON customer_branches FOR UPDATE
USING ((SELECT check_permission((SELECT auth.uid()), 'customers.update'::text)));

DROP POLICY IF EXISTS "customer_branches_read" ON customer_branches;
CREATE POLICY "customer_branches_read" ON customer_branches FOR SELECT
USING (((SELECT check_permission((SELECT auth.uid()), 'customers.read_all'::text)) OR ((SELECT check_permission((SELECT auth.uid()), 'customers.read'::text)) AND (customer_id IN ( SELECT customers.id
   FROM customers
  WHERE (customers.assigned_rep_id = (SELECT auth.uid())))))));


-- +++ customer_contacts ─────────────────────────────────
DROP POLICY IF EXISTS "customer_contacts_read" ON customer_contacts;
CREATE POLICY "customer_contacts_read" ON customer_contacts FOR SELECT
USING (((SELECT check_permission((SELECT auth.uid()), 'customers.read_all'::text)) OR ((SELECT check_permission((SELECT auth.uid()), 'customers.read'::text)) AND (customer_id IN ( SELECT customers.id
   FROM customers
  WHERE (customers.assigned_rep_id = (SELECT auth.uid())))))));

DROP POLICY IF EXISTS "customer_contacts_write" ON customer_contacts;
CREATE POLICY "customer_contacts_write" ON customer_contacts FOR ALL
USING ((SELECT check_permission((SELECT auth.uid()), 'customers.update'::text)));


-- +++ customer_credit_history ───────────────────────────
DROP POLICY IF EXISTS "credit_history_read" ON customer_credit_history;
CREATE POLICY "credit_history_read" ON customer_credit_history FOR SELECT
USING ((SELECT check_permission((SELECT auth.uid()), 'customers.read'::text)));


-- +++ customer_ledger ───────────────────────────────────
DROP POLICY IF EXISTS "cust_ledger_read" ON customer_ledger;
CREATE POLICY "cust_ledger_read" ON customer_ledger FOR SELECT
USING ((SELECT check_permission((SELECT auth.uid()), 'finance.ledger.read'::text)));

DROP POLICY IF EXISTS "cust_ledger_write" ON customer_ledger;
CREATE POLICY "cust_ledger_write" ON customer_ledger FOR ALL
USING ((SELECT check_permission((SELECT auth.uid()), 'finance.ledger.adjust'::text)));


-- +++ customers ─────────────────────────────────────────
DROP POLICY IF EXISTS "customers_delete" ON customers;
CREATE POLICY "customers_delete" ON customers FOR DELETE
USING ((SELECT check_permission((SELECT auth.uid()), 'customers.delete'::text)));

DROP POLICY IF EXISTS "customers_read" ON customers;
CREATE POLICY "customers_read" ON customers FOR SELECT
USING (((SELECT check_permission((SELECT auth.uid()), 'customers.read_all'::text)) OR ((SELECT check_permission((SELECT auth.uid()), 'customers.read'::text)) AND (assigned_rep_id = (SELECT auth.uid())))));

DROP POLICY IF EXISTS "customers_update" ON customers;
CREATE POLICY "customers_update" ON customers FOR UPDATE
USING ((SELECT check_permission((SELECT auth.uid()), 'customers.update'::text)));

DROP POLICY IF EXISTS "customers_write" ON customers;
CREATE POLICY "customers_write" ON customers FOR INSERT
WITH CHECK ((SELECT check_permission((SELECT auth.uid()), 'customers.create'::text)));


-- +++ expense_categories ────────────────────────────────
DROP POLICY IF EXISTS "exp_cat_read" ON expense_categories;
CREATE POLICY "exp_cat_read" ON expense_categories FOR SELECT
USING (((SELECT auth.uid()) IS NOT NULL));

DROP POLICY IF EXISTS "exp_cat_write" ON expense_categories;
CREATE POLICY "exp_cat_write" ON expense_categories FOR ALL
USING ((SELECT check_permission((SELECT auth.uid()), 'finance.expenses.approve'::text)));


-- +++ expenses ──────────────────────────────────────────
DROP POLICY IF EXISTS "expenses_insert" ON expenses;
CREATE POLICY "expenses_insert" ON expenses FOR INSERT
WITH CHECK ((SELECT check_permission((SELECT auth.uid()), 'finance.expenses.create'::text)));

DROP POLICY IF EXISTS "expenses_read" ON expenses;
CREATE POLICY "expenses_read" ON expenses FOR SELECT
USING (((created_by = (SELECT auth.uid())) OR (SELECT check_permission((SELECT auth.uid()), 'finance.expenses.read_all'::text))));

DROP POLICY IF EXISTS "expenses_update" ON expenses;
CREATE POLICY "expenses_update" ON expenses FOR UPDATE
USING ((((created_by = (SELECT auth.uid())) AND (status = 'draft'::text)) OR (SELECT check_permission((SELECT auth.uid()), 'finance.expenses.approve'::text))))
WITH CHECK (((SELECT check_permission((SELECT auth.uid()), 'finance.expenses.approve'::text)) OR (status = ANY (ARRAY['draft'::text, 'pending_approval'::text]))));


-- +++ feature_flags ─────────────────────────────────────
DROP POLICY IF EXISTS "flags_select" ON feature_flags;
CREATE POLICY "flags_select" ON feature_flags FOR SELECT
USING (((SELECT auth.uid()) IS NOT NULL));

DROP POLICY IF EXISTS "flags_write" ON feature_flags;
CREATE POLICY "flags_write" ON feature_flags FOR ALL
USING ((SELECT check_permission((SELECT auth.uid()), 'settings.update'::text)));


-- +++ governorates ──────────────────────────────────────
DROP POLICY IF EXISTS "geo_read" ON governorates;
CREATE POLICY "geo_read" ON governorates FOR SELECT
USING (((SELECT auth.uid()) IS NOT NULL));


-- +++ hr_advance_installments ───────────────────────────
DROP POLICY IF EXISTS "hr_inst_read" ON hr_advance_installments;
CREATE POLICY "hr_inst_read" ON hr_advance_installments FOR SELECT
USING (((advance_id IN ( SELECT hr_advances.id
   FROM hr_advances
  WHERE (hr_advances.employee_id IN ( SELECT hr_employees.id
           FROM hr_employees
          WHERE (hr_employees.user_id = (SELECT auth.uid())))))) OR (SELECT check_permission((SELECT auth.uid()), 'hr.advances.read'::text))));

DROP POLICY IF EXISTS "hr_inst_write" ON hr_advance_installments;
CREATE POLICY "hr_inst_write" ON hr_advance_installments FOR ALL
USING ((SELECT check_permission((SELECT auth.uid()), 'hr.payroll.calculate'::text)));


-- +++ hr_advances ───────────────────────────────────────
DROP POLICY IF EXISTS "hr_adv_insert" ON hr_advances;
CREATE POLICY "hr_adv_insert" ON hr_advances FOR INSERT
WITH CHECK (((employee_id IN ( SELECT hr_employees.id
   FROM hr_employees
  WHERE (hr_employees.user_id = (SELECT auth.uid())))) OR (SELECT check_permission((SELECT auth.uid()), 'hr.advances.create'::text))));

DROP POLICY IF EXISTS "hr_adv_read" ON hr_advances;
CREATE POLICY "hr_adv_read" ON hr_advances FOR SELECT
USING (((employee_id IN ( SELECT hr_employees.id
   FROM hr_employees
  WHERE (hr_employees.user_id = (SELECT auth.uid())))) OR (SELECT check_permission((SELECT auth.uid()), 'hr.advances.read'::text))));

DROP POLICY IF EXISTS "hr_adv_update" ON hr_advances;
CREATE POLICY "hr_adv_update" ON hr_advances FOR UPDATE
USING ((SELECT check_permission((SELECT auth.uid()), 'hr.advances.approve'::text)));


-- +++ hr_attendance_alerts ──────────────────────────────
DROP POLICY IF EXISTS "hr_attendance_alerts_select" ON hr_attendance_alerts;
CREATE POLICY "hr_attendance_alerts_select" ON hr_attendance_alerts FOR SELECT
USING (((employee_id IN ( SELECT hr_employees.id
   FROM hr_employees
  WHERE (hr_employees.user_id = (SELECT auth.uid())))) OR (SELECT check_permission((SELECT auth.uid()), 'hr.attendance.read'::text)) OR (SELECT check_permission((SELECT auth.uid()), 'hr.payroll.read'::text)) OR (SELECT check_permission((SELECT auth.uid()), 'hr.permissions.approve'::text))));

DROP POLICY IF EXISTS "hr_attendance_alerts_update" ON hr_attendance_alerts;
CREATE POLICY "hr_attendance_alerts_update" ON hr_attendance_alerts FOR UPDATE
USING (((SELECT check_permission((SELECT auth.uid()), 'hr.attendance.edit'::text)) OR (SELECT check_permission((SELECT auth.uid()), 'hr.permissions.approve'::text)) OR (SELECT check_permission((SELECT auth.uid()), 'hr.payroll.approve'::text))))
WITH CHECK (((SELECT check_permission((SELECT auth.uid()), 'hr.attendance.edit'::text)) OR (SELECT check_permission((SELECT auth.uid()), 'hr.permissions.approve'::text)) OR (SELECT check_permission((SELECT auth.uid()), 'hr.payroll.approve'::text))));


-- +++ hr_attendance_days ────────────────────────────────
DROP POLICY IF EXISTS "hr_att_read" ON hr_attendance_days;
CREATE POLICY "hr_att_read" ON hr_attendance_days FOR SELECT
USING (((employee_id IN ( SELECT hr_employees.id
   FROM hr_employees
  WHERE (hr_employees.user_id = (SELECT auth.uid())))) OR (SELECT check_permission((SELECT auth.uid()), 'hr.attendance.read'::text))));

DROP POLICY IF EXISTS "hr_att_write" ON hr_attendance_days;
CREATE POLICY "hr_att_write" ON hr_attendance_days FOR ALL
USING ((SELECT check_permission((SELECT auth.uid()), 'hr.attendance.create'::text)));


-- +++ hr_attendance_logs ────────────────────────────────
DROP POLICY IF EXISTS "hr_logs_insert" ON hr_attendance_logs;
CREATE POLICY "hr_logs_insert" ON hr_attendance_logs FOR INSERT
WITH CHECK (((SELECT auth.uid()) IS NOT NULL));

DROP POLICY IF EXISTS "hr_logs_read" ON hr_attendance_logs;
CREATE POLICY "hr_logs_read" ON hr_attendance_logs FOR SELECT
USING (((employee_id IN ( SELECT hr_employees.id
   FROM hr_employees
  WHERE (hr_employees.user_id = (SELECT auth.uid())))) OR (SELECT check_permission((SELECT auth.uid()), 'hr.attendance.read'::text))));


-- +++ hr_commission_records ─────────────────────────────
DROP POLICY IF EXISTS "hr_cr_read" ON hr_commission_records;
CREATE POLICY "hr_cr_read" ON hr_commission_records FOR SELECT
USING (((employee_id IN ( SELECT hr_employees.id
   FROM hr_employees
  WHERE (hr_employees.user_id = (SELECT auth.uid())))) OR (SELECT check_permission((SELECT auth.uid()), 'hr.payroll.read'::text))));

DROP POLICY IF EXISTS "hr_cr_write" ON hr_commission_records;
CREATE POLICY "hr_cr_write" ON hr_commission_records FOR ALL
USING ((SELECT check_permission((SELECT auth.uid()), 'hr.payroll.calculate'::text)));


-- +++ hr_commission_targets ─────────────────────────────
DROP POLICY IF EXISTS "hr_ct_read" ON hr_commission_targets;
CREATE POLICY "hr_ct_read" ON hr_commission_targets FOR SELECT
USING (((employee_id IN ( SELECT hr_employees.id
   FROM hr_employees
  WHERE (hr_employees.user_id = (SELECT auth.uid())))) OR (SELECT check_permission((SELECT auth.uid()), 'hr.payroll.read'::text))));

DROP POLICY IF EXISTS "hr_ct_write" ON hr_commission_targets;
CREATE POLICY "hr_ct_write" ON hr_commission_targets FOR ALL
USING ((SELECT check_permission((SELECT auth.uid()), 'hr.payroll.calculate'::text)));


-- +++ hr_contracts ──────────────────────────────────────
DROP POLICY IF EXISTS "hr_contracts_read" ON hr_contracts;
CREATE POLICY "hr_contracts_read" ON hr_contracts FOR SELECT
USING (((employee_id IN ( SELECT hr_employees.id
   FROM hr_employees
  WHERE (hr_employees.user_id = (SELECT auth.uid())))) OR (SELECT check_permission((SELECT auth.uid()), 'hr.employees.read'::text))));

DROP POLICY IF EXISTS "hr_contracts_write" ON hr_contracts;
CREATE POLICY "hr_contracts_write" ON hr_contracts FOR ALL
USING ((SELECT check_permission((SELECT auth.uid()), 'hr.employees.create'::text)));


-- +++ hr_delegations ────────────────────────────────────
DROP POLICY IF EXISTS "hr_deleg_read" ON hr_delegations;
CREATE POLICY "hr_deleg_read" ON hr_delegations FOR SELECT
USING (((delegator_id IN ( SELECT hr_employees.id
   FROM hr_employees
  WHERE (hr_employees.user_id = (SELECT auth.uid())))) OR (delegate_id IN ( SELECT hr_employees.id
   FROM hr_employees
  WHERE (hr_employees.user_id = (SELECT auth.uid())))) OR (SELECT check_permission((SELECT auth.uid()), 'hr.employees.read'::text))));

DROP POLICY IF EXISTS "hr_deleg_write" ON hr_delegations;
CREATE POLICY "hr_deleg_write" ON hr_delegations FOR ALL
USING ((SELECT check_permission((SELECT auth.uid()), 'hr.employees.create'::text)));


-- +++ hr_departments ────────────────────────────────────
DROP POLICY IF EXISTS "hr_depts_read" ON hr_departments;
CREATE POLICY "hr_depts_read" ON hr_departments FOR SELECT
USING (((SELECT auth.uid()) IS NOT NULL));

DROP POLICY IF EXISTS "hr_depts_write" ON hr_departments;
CREATE POLICY "hr_depts_write" ON hr_departments FOR ALL
USING ((SELECT check_permission((SELECT auth.uid()), 'hr.employees.create'::text)));


-- +++ hr_employee_documents ─────────────────────────────
DROP POLICY IF EXISTS "hr_docs_rls_read" ON hr_employee_documents;
CREATE POLICY "hr_docs_rls_read" ON hr_employee_documents FOR SELECT
USING (((employee_id IN ( SELECT hr_employees.id
   FROM hr_employees
  WHERE (hr_employees.user_id = (SELECT auth.uid())))) OR (SELECT check_permission((SELECT auth.uid()), 'hr.employees.read'::text))));

DROP POLICY IF EXISTS "hr_docs_rls_write" ON hr_employee_documents;
CREATE POLICY "hr_docs_rls_write" ON hr_employee_documents FOR ALL
USING ((SELECT check_permission((SELECT auth.uid()), 'hr.employees.create'::text)));


-- +++ hr_employees ──────────────────────────────────────
DROP POLICY IF EXISTS "hr_emp_insert" ON hr_employees;
CREATE POLICY "hr_emp_insert" ON hr_employees FOR INSERT
WITH CHECK ((SELECT check_permission((SELECT auth.uid()), 'hr.employees.create'::text)));

DROP POLICY IF EXISTS "hr_emp_read" ON hr_employees;
CREATE POLICY "hr_emp_read" ON hr_employees FOR SELECT
USING (((user_id = (SELECT auth.uid())) OR (SELECT check_permission((SELECT auth.uid()), 'hr.employees.read'::text))));

DROP POLICY IF EXISTS "hr_emp_update" ON hr_employees;
CREATE POLICY "hr_emp_update" ON hr_employees FOR UPDATE
USING ((SELECT check_permission((SELECT auth.uid()), 'hr.employees.create'::text)));


-- +++ hr_leave_balances ─────────────────────────────────
DROP POLICY IF EXISTS "hr_lb_read" ON hr_leave_balances;
CREATE POLICY "hr_lb_read" ON hr_leave_balances FOR SELECT
USING (((employee_id IN ( SELECT hr_employees.id
   FROM hr_employees
  WHERE (hr_employees.user_id = (SELECT auth.uid())))) OR (SELECT check_permission((SELECT auth.uid()), 'hr.leaves.read'::text))));

DROP POLICY IF EXISTS "hr_lb_write" ON hr_leave_balances;
CREATE POLICY "hr_lb_write" ON hr_leave_balances FOR ALL
USING ((SELECT check_permission((SELECT auth.uid()), 'hr.payroll.calculate'::text)));


-- +++ hr_leave_requests ─────────────────────────────────
DROP POLICY IF EXISTS "hr_lr_insert" ON hr_leave_requests;
CREATE POLICY "hr_lr_insert" ON hr_leave_requests FOR INSERT
WITH CHECK (((employee_id IN ( SELECT hr_employees.id
   FROM hr_employees
  WHERE (hr_employees.user_id = (SELECT auth.uid())))) OR (SELECT check_permission((SELECT auth.uid()), 'hr.leaves.create'::text))));

DROP POLICY IF EXISTS "hr_lr_read" ON hr_leave_requests;
CREATE POLICY "hr_lr_read" ON hr_leave_requests FOR SELECT
USING (((employee_id IN ( SELECT hr_employees.id
   FROM hr_employees
  WHERE (hr_employees.user_id = (SELECT auth.uid())))) OR (supervisor_id IN ( SELECT hr_employees.id
   FROM hr_employees
  WHERE (hr_employees.user_id = (SELECT auth.uid())))) OR (SELECT check_permission((SELECT auth.uid()), 'hr.leaves.read'::text))));

DROP POLICY IF EXISTS "hr_lr_update" ON hr_leave_requests;
CREATE POLICY "hr_lr_update" ON hr_leave_requests FOR UPDATE
USING ((((employee_id IN ( SELECT hr_employees.id
   FROM hr_employees
  WHERE (hr_employees.user_id = (SELECT auth.uid())))) AND (status = 'pending_supervisor'::hr_leave_request_status)) OR (SELECT check_permission((SELECT auth.uid()), 'hr.leaves.approve'::text))));


-- +++ hr_leave_types ────────────────────────────────────
DROP POLICY IF EXISTS "hr_lt_read" ON hr_leave_types;
CREATE POLICY "hr_lt_read" ON hr_leave_types FOR SELECT
USING (((SELECT auth.uid()) IS NOT NULL));

DROP POLICY IF EXISTS "hr_lt_write" ON hr_leave_types;
CREATE POLICY "hr_lt_write" ON hr_leave_types FOR ALL
USING ((SELECT check_permission((SELECT auth.uid()), 'hr.settings.update'::text)));


-- +++ hr_payroll_adjustments ────────────────────────────
DROP POLICY IF EXISTS "adj_insert" ON hr_payroll_adjustments;
CREATE POLICY "adj_insert" ON hr_payroll_adjustments FOR INSERT
TO authenticated
WITH CHECK ((SELECT check_permission((SELECT auth.uid()), 'hr.adjustments.create'::text)));

DROP POLICY IF EXISTS "adj_select" ON hr_payroll_adjustments;
CREATE POLICY "adj_select" ON hr_payroll_adjustments FOR SELECT
TO authenticated
USING (((SELECT check_permission((SELECT auth.uid()), 'hr.payroll.read'::text)) OR (SELECT check_permission((SELECT auth.uid()), 'hr.adjustments.read'::text))));

DROP POLICY IF EXISTS "adj_update" ON hr_payroll_adjustments;
CREATE POLICY "adj_update" ON hr_payroll_adjustments FOR UPDATE
TO authenticated
USING (((SELECT check_permission((SELECT auth.uid()), 'hr.adjustments.approve'::text)) OR ((created_by = (SELECT auth.uid())) AND (status = 'pending'::text))));


-- +++ hr_payroll_lines ──────────────────────────────────
DROP POLICY IF EXISTS "hr_pl_read" ON hr_payroll_lines;
CREATE POLICY "hr_pl_read" ON hr_payroll_lines FOR SELECT
USING (((employee_id IN ( SELECT hr_employees.id
   FROM hr_employees
  WHERE (hr_employees.user_id = (SELECT auth.uid())))) OR (SELECT check_permission((SELECT auth.uid()), 'hr.payroll.read'::text))));

DROP POLICY IF EXISTS "hr_pl_write" ON hr_payroll_lines;
CREATE POLICY "hr_pl_write" ON hr_payroll_lines FOR ALL
USING ((SELECT check_permission((SELECT auth.uid()), 'hr.payroll.calculate'::text)));


-- +++ hr_payroll_periods ────────────────────────────────
DROP POLICY IF EXISTS "hr_pp_read" ON hr_payroll_periods;
CREATE POLICY "hr_pp_read" ON hr_payroll_periods FOR SELECT
USING (((SELECT auth.uid()) IS NOT NULL));

DROP POLICY IF EXISTS "hr_pp_write" ON hr_payroll_periods;
CREATE POLICY "hr_pp_write" ON hr_payroll_periods FOR ALL
USING ((SELECT check_permission((SELECT auth.uid()), 'hr.payroll.calculate'::text)));


-- +++ hr_payroll_runs ───────────────────────────────────
DROP POLICY IF EXISTS "hr_pr_read" ON hr_payroll_runs;
CREATE POLICY "hr_pr_read" ON hr_payroll_runs FOR SELECT
USING ((SELECT check_permission((SELECT auth.uid()), 'hr.payroll.read'::text)));

DROP POLICY IF EXISTS "hr_pr_write" ON hr_payroll_runs;
CREATE POLICY "hr_pr_write" ON hr_payroll_runs FOR ALL
USING ((SELECT check_permission((SELECT auth.uid()), 'hr.payroll.calculate'::text)));


-- +++ hr_penalty_instances ──────────────────────────────
DROP POLICY IF EXISTS "hr_pen_inst_read" ON hr_penalty_instances;
CREATE POLICY "hr_pen_inst_read" ON hr_penalty_instances FOR SELECT
USING (((employee_id IN ( SELECT hr_employees.id
   FROM hr_employees
  WHERE (hr_employees.user_id = (SELECT auth.uid())))) OR (SELECT check_permission((SELECT auth.uid()), 'hr.attendance.read'::text))));

DROP POLICY IF EXISTS "hr_pen_inst_write" ON hr_penalty_instances;
CREATE POLICY "hr_pen_inst_write" ON hr_penalty_instances FOR ALL
USING ((SELECT check_permission((SELECT auth.uid()), 'hr.attendance.approve'::text)));


-- +++ hr_penalty_rules ──────────────────────────────────
DROP POLICY IF EXISTS "hr_pen_rules_read" ON hr_penalty_rules;
CREATE POLICY "hr_pen_rules_read" ON hr_penalty_rules FOR SELECT
USING (((SELECT auth.uid()) IS NOT NULL));

DROP POLICY IF EXISTS "hr_pen_rules_write" ON hr_penalty_rules;
CREATE POLICY "hr_pen_rules_write" ON hr_penalty_rules FOR ALL
USING ((SELECT check_permission((SELECT auth.uid()), 'hr.settings.update'::text)));


-- +++ hr_permission_requests ────────────────────────────
DROP POLICY IF EXISTS "hr_perm_insert" ON hr_permission_requests;
CREATE POLICY "hr_perm_insert" ON hr_permission_requests FOR INSERT
WITH CHECK (((employee_id IN ( SELECT hr_employees.id
   FROM hr_employees
  WHERE (hr_employees.user_id = (SELECT auth.uid())))) OR (SELECT check_permission((SELECT auth.uid()), 'hr.attendance.create'::text))));

DROP POLICY IF EXISTS "hr_perm_read" ON hr_permission_requests;
CREATE POLICY "hr_perm_read" ON hr_permission_requests FOR SELECT
USING (((employee_id IN ( SELECT hr_employees.id
   FROM hr_employees
  WHERE (hr_employees.user_id = (SELECT auth.uid())))) OR (SELECT check_permission((SELECT auth.uid()), 'hr.attendance.read'::text))));

DROP POLICY IF EXISTS "hr_perm_update" ON hr_permission_requests;
CREATE POLICY "hr_perm_update" ON hr_permission_requests FOR UPDATE
USING ((SELECT check_permission((SELECT auth.uid()), 'hr.attendance.approve'::text)));


-- +++ hr_positions ──────────────────────────────────────
DROP POLICY IF EXISTS "hr_pos_read" ON hr_positions;
CREATE POLICY "hr_pos_read" ON hr_positions FOR SELECT
USING (((SELECT auth.uid()) IS NOT NULL));

DROP POLICY IF EXISTS "hr_pos_write" ON hr_positions;
CREATE POLICY "hr_pos_write" ON hr_positions FOR ALL
USING ((SELECT check_permission((SELECT auth.uid()), 'hr.employees.create'::text)));


-- +++ hr_public_holidays ────────────────────────────────
DROP POLICY IF EXISTS "hr_holidays_read" ON hr_public_holidays;
CREATE POLICY "hr_holidays_read" ON hr_public_holidays FOR SELECT
USING (((SELECT auth.uid()) IS NOT NULL));

DROP POLICY IF EXISTS "hr_holidays_write" ON hr_public_holidays;
CREATE POLICY "hr_holidays_write" ON hr_public_holidays FOR ALL
USING ((SELECT check_permission((SELECT auth.uid()), 'hr.settings.update'::text)));


-- +++ hr_salary_history ─────────────────────────────────
DROP POLICY IF EXISTS "hr_sal_hist_read" ON hr_salary_history;
CREATE POLICY "hr_sal_hist_read" ON hr_salary_history FOR SELECT
USING (((employee_id IN ( SELECT hr_employees.id
   FROM hr_employees
  WHERE (hr_employees.user_id = (SELECT auth.uid())))) OR (SELECT check_permission((SELECT auth.uid()), 'hr.payroll.read'::text))));

DROP POLICY IF EXISTS "hr_sal_hist_write" ON hr_salary_history;
CREATE POLICY "hr_sal_hist_write" ON hr_salary_history FOR ALL
USING ((SELECT check_permission((SELECT auth.uid()), 'hr.payroll.calculate'::text)));


-- +++ hr_work_locations ─────────────────────────────────
DROP POLICY IF EXISTS "hr_locations_read" ON hr_work_locations;
CREATE POLICY "hr_locations_read" ON hr_work_locations FOR SELECT
USING ((((SELECT auth.uid()) IS NOT NULL) AND (is_active = true)));

DROP POLICY IF EXISTS "hr_locations_write" ON hr_work_locations;
CREATE POLICY "hr_locations_write" ON hr_work_locations FOR ALL
USING ((SELECT check_permission((SELECT auth.uid()), 'hr.employees.create'::text)));


-- +++ journal_entries ───────────────────────────────────
DROP POLICY IF EXISTS "je_read" ON journal_entries;
CREATE POLICY "je_read" ON journal_entries FOR SELECT
USING ((SELECT check_permission((SELECT auth.uid()), 'finance.journal.read'::text)));

DROP POLICY IF EXISTS "je_write" ON journal_entries;
CREATE POLICY "je_write" ON journal_entries FOR ALL
USING ((SELECT check_permission((SELECT auth.uid()), 'finance.journal.create'::text)));


-- +++ journal_entry_lines ───────────────────────────────
DROP POLICY IF EXISTS "je_lines_read" ON journal_entry_lines;
CREATE POLICY "je_lines_read" ON journal_entry_lines FOR SELECT
USING ((SELECT check_permission((SELECT auth.uid()), 'finance.journal.read'::text)));

DROP POLICY IF EXISTS "je_lines_write" ON journal_entry_lines;
CREATE POLICY "je_lines_write" ON journal_entry_lines FOR ALL
USING ((SELECT check_permission((SELECT auth.uid()), 'finance.journal.create'::text)));


-- +++ notification_delivery_log ─────────────────────────
DROP POLICY IF EXISTS "delivery_log_select_own" ON notification_delivery_log;
CREATE POLICY "delivery_log_select_own" ON notification_delivery_log FOR SELECT
USING ((notification_id IN ( SELECT notifications.id
   FROM notifications
  WHERE (notifications.user_id = (SELECT auth.uid())))));


-- +++ notification_preferences ──────────────────────────
DROP POLICY IF EXISTS "preferences_select_own" ON notification_preferences;
CREATE POLICY "preferences_select_own" ON notification_preferences FOR SELECT
USING (((SELECT auth.uid()) = user_id));

DROP POLICY IF EXISTS "preferences_upsert_own" ON notification_preferences;
CREATE POLICY "preferences_upsert_own" ON notification_preferences FOR ALL
USING (((SELECT auth.uid()) = user_id))
WITH CHECK (((SELECT auth.uid()) = user_id));


-- +++ notifications ─────────────────────────────────────
DROP POLICY IF EXISTS "notifications_select_own" ON notifications;
CREATE POLICY "notifications_select_own" ON notifications FOR SELECT
USING (((SELECT auth.uid()) = user_id));


-- +++ payment_receipts ──────────────────────────────────
DROP POLICY IF EXISTS "receipts_insert" ON payment_receipts;
CREATE POLICY "receipts_insert" ON payment_receipts FOR INSERT
WITH CHECK ((SELECT check_permission((SELECT auth.uid()), 'finance.payments.create'::text)));

DROP POLICY IF EXISTS "receipts_read" ON payment_receipts;
CREATE POLICY "receipts_read" ON payment_receipts FOR SELECT
USING (((created_by = (SELECT auth.uid())) OR (collected_by = (SELECT auth.uid())) OR (SELECT check_permission((SELECT auth.uid()), 'finance.payments.read_all'::text))));

DROP POLICY IF EXISTS "receipts_update" ON payment_receipts;
CREATE POLICY "receipts_update" ON payment_receipts FOR UPDATE
USING ((SELECT check_permission((SELECT auth.uid()), 'finance.payments.confirm'::text)));


-- +++ price_list_assignments ────────────────────────────
DROP POLICY IF EXISTS "price_list_assignments_read" ON price_list_assignments;
CREATE POLICY "price_list_assignments_read" ON price_list_assignments FOR SELECT
USING ((SELECT check_permission((SELECT auth.uid()), 'price_lists.read'::text)));

DROP POLICY IF EXISTS "price_list_assignments_write" ON price_list_assignments;
CREATE POLICY "price_list_assignments_write" ON price_list_assignments FOR ALL
USING ((SELECT check_permission((SELECT auth.uid()), 'price_lists.update'::text)));


-- +++ price_list_items ──────────────────────────────────
DROP POLICY IF EXISTS "price_list_items_read" ON price_list_items;
CREATE POLICY "price_list_items_read" ON price_list_items FOR SELECT
USING ((SELECT check_permission((SELECT auth.uid()), 'price_lists.read'::text)));

DROP POLICY IF EXISTS "price_list_items_write" ON price_list_items;
CREATE POLICY "price_list_items_write" ON price_list_items FOR ALL
USING ((SELECT check_permission((SELECT auth.uid()), 'price_lists.update'::text)));


-- +++ price_lists ───────────────────────────────────────
DROP POLICY IF EXISTS "price_lists_read" ON price_lists;
CREATE POLICY "price_lists_read" ON price_lists FOR SELECT
USING ((SELECT check_permission((SELECT auth.uid()), 'price_lists.read'::text)));

DROP POLICY IF EXISTS "price_lists_write" ON price_lists;
CREATE POLICY "price_lists_write" ON price_lists FOR ALL
USING ((SELECT check_permission((SELECT auth.uid()), 'price_lists.update'::text)));


-- +++ product_bundle_items ──────────────────────────────
DROP POLICY IF EXISTS "bundle_items_read" ON product_bundle_items;
CREATE POLICY "bundle_items_read" ON product_bundle_items FOR SELECT
USING ((SELECT check_permission((SELECT auth.uid()), 'products.read'::text)));

DROP POLICY IF EXISTS "bundle_items_write" ON product_bundle_items;
CREATE POLICY "bundle_items_write" ON product_bundle_items FOR ALL
USING ((SELECT check_permission((SELECT auth.uid()), 'products.create'::text)));


-- +++ product_bundles ───────────────────────────────────
DROP POLICY IF EXISTS "bundles_read" ON product_bundles;
CREATE POLICY "bundles_read" ON product_bundles FOR SELECT
USING ((SELECT check_permission((SELECT auth.uid()), 'products.read'::text)));

DROP POLICY IF EXISTS "bundles_write" ON product_bundles;
CREATE POLICY "bundles_write" ON product_bundles FOR ALL
USING ((SELECT check_permission((SELECT auth.uid()), 'products.create'::text)));


-- +++ product_categories ────────────────────────────────
DROP POLICY IF EXISTS "categories_read" ON product_categories;
CREATE POLICY "categories_read" ON product_categories FOR SELECT
USING ((SELECT check_permission((SELECT auth.uid()), 'products.read'::text)));

DROP POLICY IF EXISTS "categories_write" ON product_categories;
CREATE POLICY "categories_write" ON product_categories FOR ALL
USING ((SELECT check_permission((SELECT auth.uid()), 'categories.create'::text)));


-- +++ product_units ─────────────────────────────────────
DROP POLICY IF EXISTS "product_units_read" ON product_units;
CREATE POLICY "product_units_read" ON product_units FOR SELECT
USING ((SELECT check_permission((SELECT auth.uid()), 'products.read'::text)));

DROP POLICY IF EXISTS "product_units_write" ON product_units;
CREATE POLICY "product_units_write" ON product_units FOR ALL
USING ((SELECT check_permission((SELECT auth.uid()), 'products.create'::text)));


-- +++ products ──────────────────────────────────────────
DROP POLICY IF EXISTS "products_read" ON products;
CREATE POLICY "products_read" ON products FOR SELECT
USING ((SELECT check_permission((SELECT auth.uid()), 'products.read'::text)));

DROP POLICY IF EXISTS "products_write" ON products;
CREATE POLICY "products_write" ON products FOR ALL
USING ((SELECT check_permission((SELECT auth.uid()), 'products.create'::text)));


-- +++ profiles ──────────────────────────────────────────
DROP POLICY IF EXISTS "profiles_select" ON profiles;
CREATE POLICY "profiles_select" ON profiles FOR SELECT
USING (((id = (SELECT auth.uid())) OR (SELECT check_permission((SELECT auth.uid()), 'auth.users.read'::text))));

DROP POLICY IF EXISTS "profiles_update" ON profiles;
CREATE POLICY "profiles_update" ON profiles FOR UPDATE
USING (((id = (SELECT auth.uid())) OR (SELECT check_permission((SELECT auth.uid()), 'auth.users.update'::text))));


-- +++ purchase_invoice_items ────────────────────────────
DROP POLICY IF EXISTS "pii_insert" ON purchase_invoice_items;
CREATE POLICY "pii_insert" ON purchase_invoice_items FOR INSERT
WITH CHECK ((SELECT check_permission((SELECT auth.uid()), 'procurement.invoices.create'::text)));

DROP POLICY IF EXISTS "pii_read" ON purchase_invoice_items;
CREATE POLICY "pii_read" ON purchase_invoice_items FOR SELECT
USING ((SELECT check_permission((SELECT auth.uid()), 'procurement.invoices.read'::text)));

DROP POLICY IF EXISTS "pii_update" ON purchase_invoice_items;
CREATE POLICY "pii_update" ON purchase_invoice_items FOR UPDATE
USING ((SELECT check_permission((SELECT auth.uid()), 'procurement.invoices.receive'::text)));


-- +++ purchase_invoices ─────────────────────────────────
DROP POLICY IF EXISTS "pi_insert" ON purchase_invoices;
CREATE POLICY "pi_insert" ON purchase_invoices FOR INSERT
WITH CHECK ((SELECT check_permission((SELECT auth.uid()), 'procurement.invoices.create'::text)));

DROP POLICY IF EXISTS "pi_read" ON purchase_invoices;
CREATE POLICY "pi_read" ON purchase_invoices FOR SELECT
USING ((SELECT check_permission((SELECT auth.uid()), 'procurement.invoices.read'::text)));

DROP POLICY IF EXISTS "pi_update" ON purchase_invoices;
CREATE POLICY "pi_update" ON purchase_invoices FOR UPDATE
USING (((SELECT check_permission((SELECT auth.uid()), 'procurement.invoices.receive'::text)) OR (SELECT check_permission((SELECT auth.uid()), 'procurement.invoices.bill'::text)) OR (SELECT check_permission((SELECT auth.uid()), 'procurement.invoices.pay'::text))));


-- +++ purchase_return_items ─────────────────────────────
DROP POLICY IF EXISTS "pri_insert" ON purchase_return_items;
CREATE POLICY "pri_insert" ON purchase_return_items FOR INSERT
WITH CHECK ((SELECT check_permission((SELECT auth.uid()), 'procurement.returns.create'::text)));

DROP POLICY IF EXISTS "pri_read" ON purchase_return_items;
CREATE POLICY "pri_read" ON purchase_return_items FOR SELECT
USING ((SELECT check_permission((SELECT auth.uid()), 'procurement.returns.read'::text)));

DROP POLICY IF EXISTS "pri_update" ON purchase_return_items;
CREATE POLICY "pri_update" ON purchase_return_items FOR UPDATE
USING ((SELECT check_permission((SELECT auth.uid()), 'procurement.returns.confirm'::text)));


-- +++ purchase_returns ──────────────────────────────────
DROP POLICY IF EXISTS "pr_insert" ON purchase_returns;
CREATE POLICY "pr_insert" ON purchase_returns FOR INSERT
WITH CHECK ((SELECT check_permission((SELECT auth.uid()), 'procurement.returns.create'::text)));

DROP POLICY IF EXISTS "pr_read" ON purchase_returns;
CREATE POLICY "pr_read" ON purchase_returns FOR SELECT
USING ((SELECT check_permission((SELECT auth.uid()), 'procurement.returns.read'::text)));

DROP POLICY IF EXISTS "pr_update" ON purchase_returns;
CREATE POLICY "pr_update" ON purchase_returns FOR UPDATE
USING (((SELECT check_permission((SELECT auth.uid()), 'procurement.returns.create'::text)) OR (SELECT check_permission((SELECT auth.uid()), 'procurement.returns.confirm'::text))));


-- +++ push_subscriptions ────────────────────────────────
DROP POLICY IF EXISTS "push_delete_own" ON push_subscriptions;
CREATE POLICY "push_delete_own" ON push_subscriptions FOR DELETE
USING (((SELECT auth.uid()) = user_id));

DROP POLICY IF EXISTS "push_insert_own" ON push_subscriptions;
CREATE POLICY "push_insert_own" ON push_subscriptions FOR INSERT
WITH CHECK (((SELECT auth.uid()) = user_id));

DROP POLICY IF EXISTS "push_select_own" ON push_subscriptions;
CREATE POLICY "push_select_own" ON push_subscriptions FOR SELECT
USING (((SELECT auth.uid()) = user_id));

DROP POLICY IF EXISTS "push_update_own" ON push_subscriptions;
CREATE POLICY "push_update_own" ON push_subscriptions FOR UPDATE
USING (((SELECT auth.uid()) = user_id));


-- +++ role_permissions ──────────────────────────────────
DROP POLICY IF EXISTS "role_perms_delete" ON role_permissions;
CREATE POLICY "role_perms_delete" ON role_permissions FOR DELETE
USING ((SELECT check_permission((SELECT auth.uid()), 'auth.roles.update'::text)));

DROP POLICY IF EXISTS "role_perms_insert" ON role_permissions;
CREATE POLICY "role_perms_insert" ON role_permissions FOR INSERT
WITH CHECK ((SELECT check_permission((SELECT auth.uid()), 'auth.roles.update'::text)));

DROP POLICY IF EXISTS "role_perms_select" ON role_permissions;
CREATE POLICY "role_perms_select" ON role_permissions FOR SELECT
USING (((SELECT auth.uid()) IS NOT NULL));

DROP POLICY IF EXISTS "role_perms_update" ON role_permissions;
CREATE POLICY "role_perms_update" ON role_permissions FOR UPDATE
USING ((SELECT check_permission((SELECT auth.uid()), 'auth.roles.update'::text)));


-- +++ roles ─────────────────────────────────────────────
DROP POLICY IF EXISTS "roles_delete" ON roles;
CREATE POLICY "roles_delete" ON roles FOR DELETE
USING (((NOT is_system) AND (SELECT check_permission((SELECT auth.uid()), 'auth.roles.delete'::text))));

DROP POLICY IF EXISTS "roles_insert" ON roles;
CREATE POLICY "roles_insert" ON roles FOR INSERT
WITH CHECK ((SELECT check_permission((SELECT auth.uid()), 'auth.roles.create'::text)));

DROP POLICY IF EXISTS "roles_select" ON roles;
CREATE POLICY "roles_select" ON roles FOR SELECT
USING (((SELECT auth.uid()) IS NOT NULL));

DROP POLICY IF EXISTS "roles_update" ON roles;
CREATE POLICY "roles_update" ON roles FOR UPDATE
USING (((NOT is_system) AND (SELECT check_permission((SELECT auth.uid()), 'auth.roles.update'::text))));


-- +++ sales_order_items ─────────────────────────────────
DROP POLICY IF EXISTS "soi_read" ON sales_order_items;
CREATE POLICY "soi_read" ON sales_order_items FOR SELECT
USING ((EXISTS ( SELECT 1
   FROM sales_orders so
  WHERE ((so.id = sales_order_items.order_id) AND ((so.rep_id = (SELECT auth.uid())) OR (so.created_by_id = (SELECT auth.uid())) OR (SELECT check_permission((SELECT auth.uid()), 'sales.orders.read_all'::text)))))));

DROP POLICY IF EXISTS "soi_write" ON sales_order_items;
CREATE POLICY "soi_write" ON sales_order_items FOR ALL
USING ((EXISTS ( SELECT 1
   FROM sales_orders so
  WHERE (((so.id = sales_order_items.order_id) AND ((so.status = 'draft'::sales_order_status) AND ((so.rep_id = (SELECT auth.uid())) OR (so.created_by_id = (SELECT auth.uid()))))) OR (SELECT check_permission((SELECT auth.uid()), 'sales.orders.read_all'::text))))));


-- +++ sales_orders ──────────────────────────────────────
DROP POLICY IF EXISTS "so_insert" ON sales_orders;
CREATE POLICY "so_insert" ON sales_orders FOR INSERT
WITH CHECK ((SELECT check_permission((SELECT auth.uid()), 'sales.orders.create'::text)));

DROP POLICY IF EXISTS "so_read" ON sales_orders;
CREATE POLICY "so_read" ON sales_orders FOR SELECT
USING (((rep_id = (SELECT auth.uid())) OR (created_by_id = (SELECT auth.uid())) OR (SELECT check_permission((SELECT auth.uid()), 'sales.orders.read_all'::text))));

DROP POLICY IF EXISTS "so_update" ON sales_orders;
CREATE POLICY "so_update" ON sales_orders FOR UPDATE
USING ((((status = 'draft'::sales_order_status) AND ((rep_id = (SELECT auth.uid())) OR (created_by_id = (SELECT auth.uid())))) OR (SELECT check_permission((SELECT auth.uid()), 'sales.orders.read_all'::text))));


-- +++ sales_return_items ────────────────────────────────
DROP POLICY IF EXISTS "sri_read" ON sales_return_items;
CREATE POLICY "sri_read" ON sales_return_items FOR SELECT
USING ((EXISTS ( SELECT 1
   FROM sales_returns sr
  WHERE ((sr.id = sales_return_items.return_id) AND ((sr.created_by = (SELECT auth.uid())) OR (SELECT check_permission((SELECT auth.uid()), 'sales.returns.read'::text)))))));

DROP POLICY IF EXISTS "sri_write" ON sales_return_items;
CREATE POLICY "sri_write" ON sales_return_items FOR ALL
USING ((EXISTS ( SELECT 1
   FROM sales_returns sr
  WHERE ((sr.id = sales_return_items.return_id) AND (sr.status = 'draft'::sales_return_status) AND ((sr.created_by = (SELECT auth.uid())) OR (SELECT check_permission((SELECT auth.uid()), 'sales.returns.confirm'::text)))))));


-- +++ sales_returns ─────────────────────────────────────
DROP POLICY IF EXISTS "sr_insert" ON sales_returns;
CREATE POLICY "sr_insert" ON sales_returns FOR INSERT
WITH CHECK ((SELECT check_permission((SELECT auth.uid()), 'sales.returns.create'::text)));

DROP POLICY IF EXISTS "sr_read" ON sales_returns;
CREATE POLICY "sr_read" ON sales_returns FOR SELECT
USING (((created_by = (SELECT auth.uid())) OR (SELECT check_permission((SELECT auth.uid()), 'sales.returns.read'::text))));

DROP POLICY IF EXISTS "sr_update" ON sales_returns;
CREATE POLICY "sr_update" ON sales_returns FOR UPDATE
USING ((((status = 'draft'::sales_return_status) AND (created_by = (SELECT auth.uid()))) OR (SELECT check_permission((SELECT auth.uid()), 'sales.returns.confirm'::text))));


-- +++ shipping_companies ────────────────────────────────
DROP POLICY IF EXISTS "shipping_read" ON shipping_companies;
CREATE POLICY "shipping_read" ON shipping_companies FOR SELECT
USING (((SELECT auth.uid()) IS NOT NULL));

DROP POLICY IF EXISTS "shipping_write" ON shipping_companies;
CREATE POLICY "shipping_write" ON shipping_companies FOR ALL
USING ((SELECT check_permission((SELECT auth.uid()), 'sales.shipping.manage'::text)));


-- +++ stock ─────────────────────────────────────────────
DROP POLICY IF EXISTS "stock_read" ON stock;
CREATE POLICY "stock_read" ON stock FOR SELECT
USING (((SELECT check_permission((SELECT auth.uid()), 'inventory.read_all'::text)) OR ((SELECT check_permission((SELECT auth.uid()), 'inventory.read'::text)) AND (warehouse_id IN ( SELECT user_warehouse_ids_set() AS user_warehouse_ids_set)))));


-- +++ stock_adjustment_items ────────────────────────────
DROP POLICY IF EXISTS "adjustment_items_read" ON stock_adjustment_items;
CREATE POLICY "adjustment_items_read" ON stock_adjustment_items FOR SELECT
USING (((SELECT check_permission((SELECT auth.uid()), 'inventory.read_all'::text)) OR (adjustment_id IN ( SELECT stock_adjustments.id
   FROM stock_adjustments
  WHERE ((stock_adjustments.created_by = (SELECT auth.uid())) OR (stock_adjustments.warehouse_id IN ( SELECT user_warehouse_ids_set() AS user_warehouse_ids_set)))))));

DROP POLICY IF EXISTS "adjustment_items_write" ON stock_adjustment_items;
CREATE POLICY "adjustment_items_write" ON stock_adjustment_items FOR ALL
USING ((SELECT check_permission((SELECT auth.uid()), 'inventory.adjustments.create'::text)));


-- +++ stock_adjustments ─────────────────────────────────
DROP POLICY IF EXISTS "adjustments_read" ON stock_adjustments;
CREATE POLICY "adjustments_read" ON stock_adjustments FOR SELECT
USING (((SELECT check_permission((SELECT auth.uid()), 'inventory.read_all'::text)) OR (created_by = (SELECT auth.uid())) OR ((SELECT check_permission((SELECT auth.uid()), 'inventory.adjustments.read'::text)) AND (warehouse_id IN ( SELECT user_warehouse_ids_set() AS user_warehouse_ids_set)))));

DROP POLICY IF EXISTS "adjustments_write" ON stock_adjustments;
CREATE POLICY "adjustments_write" ON stock_adjustments FOR ALL
USING ((SELECT check_permission((SELECT auth.uid()), 'inventory.adjustments.create'::text)));


-- +++ stock_batches ─────────────────────────────────────
DROP POLICY IF EXISTS "stock_batches_read" ON stock_batches;
CREATE POLICY "stock_batches_read" ON stock_batches FOR SELECT
USING (((SELECT check_permission((SELECT auth.uid()), 'inventory.read_all'::text)) OR ((SELECT check_permission((SELECT auth.uid()), 'inventory.read'::text)) AND (stock_id IN ( SELECT stock.id
   FROM stock
  WHERE (stock.warehouse_id IN ( SELECT user_warehouse_ids_set() AS user_warehouse_ids_set)))))));


-- +++ stock_movements ───────────────────────────────────
DROP POLICY IF EXISTS "stock_movements_read" ON stock_movements;
CREATE POLICY "stock_movements_read" ON stock_movements FOR SELECT
USING (((SELECT check_permission((SELECT auth.uid()), 'inventory.read_all'::text)) OR ((SELECT check_permission((SELECT auth.uid()), 'inventory.read'::text)) AND (warehouse_id IN ( SELECT user_warehouse_ids_set() AS user_warehouse_ids_set)))));


-- +++ stock_transfer_items ──────────────────────────────
DROP POLICY IF EXISTS "transfer_items_read" ON stock_transfer_items;
CREATE POLICY "transfer_items_read" ON stock_transfer_items FOR SELECT
USING (((SELECT check_permission((SELECT auth.uid()), 'inventory.read_all'::text)) OR (transfer_id IN ( SELECT stock_transfers.id
   FROM stock_transfers
  WHERE ((stock_transfers.requested_by = (SELECT auth.uid())) OR (stock_transfers.from_warehouse_id IN ( SELECT user_warehouse_ids_set() AS user_warehouse_ids_set)) OR (stock_transfers.to_warehouse_id IN ( SELECT user_warehouse_ids_set() AS user_warehouse_ids_set)))))));

DROP POLICY IF EXISTS "transfer_items_write" ON stock_transfer_items;
CREATE POLICY "transfer_items_write" ON stock_transfer_items FOR ALL
USING ((SELECT check_permission((SELECT auth.uid()), 'inventory.transfers.create'::text)));


-- +++ stock_transfers ───────────────────────────────────
DROP POLICY IF EXISTS "transfers_read" ON stock_transfers;
CREATE POLICY "transfers_read" ON stock_transfers FOR SELECT
USING (((SELECT check_permission((SELECT auth.uid()), 'inventory.read_all'::text)) OR (requested_by = (SELECT auth.uid())) OR ((SELECT check_permission((SELECT auth.uid()), 'inventory.transfers.read'::text)) AND ((from_warehouse_id IN ( SELECT user_warehouse_ids_set() AS user_warehouse_ids_set)) OR (to_warehouse_id IN ( SELECT user_warehouse_ids_set() AS user_warehouse_ids_set))))));

DROP POLICY IF EXISTS "transfers_write" ON stock_transfers;
CREATE POLICY "transfers_write" ON stock_transfers FOR ALL
USING ((SELECT check_permission((SELECT auth.uid()), 'inventory.transfers.create'::text)));


-- +++ supplier_contacts ─────────────────────────────────
DROP POLICY IF EXISTS "supplier_contacts_read" ON supplier_contacts;
CREATE POLICY "supplier_contacts_read" ON supplier_contacts FOR SELECT
USING ((SELECT check_permission((SELECT auth.uid()), 'suppliers.read'::text)));

DROP POLICY IF EXISTS "supplier_contacts_write" ON supplier_contacts;
CREATE POLICY "supplier_contacts_write" ON supplier_contacts FOR ALL
USING ((SELECT check_permission((SELECT auth.uid()), 'suppliers.update'::text)));


-- +++ supplier_ledger ───────────────────────────────────
DROP POLICY IF EXISTS "supp_ledger_read" ON supplier_ledger;
CREATE POLICY "supp_ledger_read" ON supplier_ledger FOR SELECT
USING ((SELECT check_permission((SELECT auth.uid()), 'finance.ledger.read'::text)));

DROP POLICY IF EXISTS "supp_ledger_write" ON supplier_ledger;
CREATE POLICY "supp_ledger_write" ON supplier_ledger FOR ALL
USING ((SELECT check_permission((SELECT auth.uid()), 'finance.ledger.adjust'::text)));


-- +++ supplier_payment_reminders ────────────────────────
DROP POLICY IF EXISTS "payment_reminders_read" ON supplier_payment_reminders;
CREATE POLICY "payment_reminders_read" ON supplier_payment_reminders FOR SELECT
USING ((SELECT check_permission((SELECT auth.uid()), 'suppliers.read'::text)));

DROP POLICY IF EXISTS "payment_reminders_write" ON supplier_payment_reminders;
CREATE POLICY "payment_reminders_write" ON supplier_payment_reminders FOR ALL
USING ((SELECT check_permission((SELECT auth.uid()), 'suppliers.update'::text)));


-- +++ supplier_payment_vouchers ─────────────────────────
DROP POLICY IF EXISTS "spv_insert" ON supplier_payment_vouchers;
CREATE POLICY "spv_insert" ON supplier_payment_vouchers FOR INSERT
WITH CHECK ((SELECT check_permission((SELECT auth.uid()), 'procurement.invoices.pay'::text)));

DROP POLICY IF EXISTS "spv_read" ON supplier_payment_vouchers;
CREATE POLICY "spv_read" ON supplier_payment_vouchers FOR SELECT
USING (((SELECT check_permission((SELECT auth.uid()), 'procurement.invoices.pay'::text)) OR (SELECT check_permission((SELECT auth.uid()), 'procurement.invoices.read'::text))));

DROP POLICY IF EXISTS "spv_update" ON supplier_payment_vouchers;
CREATE POLICY "spv_update" ON supplier_payment_vouchers FOR UPDATE
USING ((SELECT check_permission((SELECT auth.uid()), 'procurement.invoices.pay'::text)));


-- +++ suppliers ─────────────────────────────────────────
DROP POLICY IF EXISTS "suppliers_delete" ON suppliers;
CREATE POLICY "suppliers_delete" ON suppliers FOR DELETE
USING ((SELECT check_permission((SELECT auth.uid()), 'suppliers.delete'::text)));

DROP POLICY IF EXISTS "suppliers_read" ON suppliers;
CREATE POLICY "suppliers_read" ON suppliers FOR SELECT
USING ((SELECT check_permission((SELECT auth.uid()), 'suppliers.read'::text)));

DROP POLICY IF EXISTS "suppliers_update" ON suppliers;
CREATE POLICY "suppliers_update" ON suppliers FOR UPDATE
USING ((SELECT check_permission((SELECT auth.uid()), 'suppliers.update'::text)));

DROP POLICY IF EXISTS "suppliers_write" ON suppliers;
CREATE POLICY "suppliers_write" ON suppliers FOR INSERT
WITH CHECK ((SELECT check_permission((SELECT auth.uid()), 'suppliers.create'::text)));


-- +++ target_adjustments ────────────────────────────────
DROP POLICY IF EXISTS "ta_read" ON target_adjustments;
CREATE POLICY "ta_read" ON target_adjustments FOR SELECT
USING (((SELECT check_permission((SELECT auth.uid()), 'targets.read_team'::text)) OR (SELECT check_permission((SELECT auth.uid()), 'targets.read_all'::text))));


-- +++ target_customers ──────────────────────────────────
DROP POLICY IF EXISTS "tc_read" ON target_customers;
CREATE POLICY "tc_read" ON target_customers FOR SELECT
USING (((EXISTS ( SELECT 1
   FROM targets t
  WHERE ((t.id = target_customers.target_id) AND (t.assigned_by = (SELECT auth.uid()))))) OR (EXISTS ( SELECT 1
   FROM (targets t
     JOIN hr_employees he ON ((he.id = t.scope_id)))
  WHERE ((t.id = target_customers.target_id) AND ((t.scope)::text = 'individual'::text) AND (he.user_id = (SELECT auth.uid()))))) OR (SELECT check_permission((SELECT auth.uid()), 'targets.read_all'::text)) OR (SELECT check_permission((SELECT auth.uid()), 'targets.rewards.view'::text)) OR (SELECT check_permission((SELECT auth.uid()), 'targets.rewards.configure'::text))));

DROP POLICY IF EXISTS "tc_write" ON target_customers;
CREATE POLICY "tc_write" ON target_customers FOR ALL
USING (((SELECT check_permission((SELECT auth.uid()), 'targets.create'::text)) OR (SELECT check_permission((SELECT auth.uid()), 'targets.read_all'::text)) OR (SELECT check_permission((SELECT auth.uid()), 'targets.rewards.configure'::text))));


-- +++ target_payout_clawbacks ───────────────────────────
DROP POLICY IF EXISTS "clawback_select" ON target_payout_clawbacks;
CREATE POLICY "clawback_select" ON target_payout_clawbacks FOR SELECT
TO authenticated
USING (((SELECT check_permission((SELECT auth.uid()), 'hr.payroll.read'::text)) OR (SELECT check_permission((SELECT auth.uid()), 'hr.adjustments.read'::text)) OR (SELECT check_permission((SELECT auth.uid()), 'targets.view'::text))));


-- +++ target_progress ───────────────────────────────────
DROP POLICY IF EXISTS "tp_read" ON target_progress;
CREATE POLICY "tp_read" ON target_progress FOR SELECT
USING ((EXISTS ( SELECT 1
   FROM targets t
  WHERE ((t.id = target_progress.target_id) AND ((((t.scope)::text = 'individual'::text) AND (t.scope_id IN ( SELECT hr_employees.id
           FROM hr_employees
          WHERE (hr_employees.user_id = (SELECT auth.uid()))))) OR ((SELECT check_permission((SELECT auth.uid()), 'targets.read_team'::text)) AND ((((t.scope)::text = 'branch'::text) AND (t.scope_id = ( SELECT hr_employees.branch_id
           FROM hr_employees
          WHERE (hr_employees.user_id = (SELECT auth.uid()))
         LIMIT 1))) OR (((t.scope)::text = 'individual'::text) AND (t.scope_id IN ( SELECT hr_employees.id
           FROM hr_employees
          WHERE (hr_employees.branch_id = ( SELECT hr_employees_1.branch_id
                   FROM hr_employees hr_employees_1
                  WHERE (hr_employees_1.user_id = (SELECT auth.uid()))
                 LIMIT 1))))))) OR (SELECT check_permission((SELECT auth.uid()), 'targets.read_all'::text)))))));


-- +++ target_reward_payouts ─────────────────────────────
DROP POLICY IF EXISTS "trp_read" ON target_reward_payouts;
CREATE POLICY "trp_read" ON target_reward_payouts FOR SELECT
USING (((employee_id IN ( SELECT hr_employees.id
   FROM hr_employees
  WHERE (hr_employees.user_id = (SELECT auth.uid())))) OR (SELECT check_permission((SELECT auth.uid()), 'targets.read_all'::text)) OR (SELECT check_permission((SELECT auth.uid()), 'hr.payroll.read'::text))));


-- +++ target_reward_tiers ───────────────────────────────
DROP POLICY IF EXISTS "trt_read" ON target_reward_tiers;
CREATE POLICY "trt_read" ON target_reward_tiers FOR SELECT
USING (((EXISTS ( SELECT 1
   FROM targets t
  WHERE ((t.id = target_reward_tiers.target_id) AND (t.assigned_by = (SELECT auth.uid()))))) OR (EXISTS ( SELECT 1
   FROM (targets t
     JOIN hr_employees he ON ((he.id = t.scope_id)))
  WHERE ((t.id = target_reward_tiers.target_id) AND ((t.scope)::text = 'individual'::text) AND (he.user_id = (SELECT auth.uid()))))) OR (SELECT check_permission((SELECT auth.uid()), 'targets.read_all'::text)) OR (SELECT check_permission((SELECT auth.uid()), 'targets.rewards.view'::text)) OR (SELECT check_permission((SELECT auth.uid()), 'targets.rewards.configure'::text))));

DROP POLICY IF EXISTS "trt_write" ON target_reward_tiers;
CREATE POLICY "trt_write" ON target_reward_tiers FOR ALL
USING (((SELECT check_permission((SELECT auth.uid()), 'targets.create'::text)) OR (SELECT check_permission((SELECT auth.uid()), 'targets.read_all'::text)) OR (SELECT check_permission((SELECT auth.uid()), 'targets.rewards.configure'::text))));


-- +++ target_types ──────────────────────────────────────
DROP POLICY IF EXISTS "target_types_read" ON target_types;
CREATE POLICY "target_types_read" ON target_types FOR SELECT
USING (((SELECT auth.uid()) IS NOT NULL));

DROP POLICY IF EXISTS "tgt_types_read" ON target_types;
CREATE POLICY "tgt_types_read" ON target_types FOR SELECT
USING (((SELECT auth.uid()) IS NOT NULL));

DROP POLICY IF EXISTS "tgt_types_write" ON target_types;
CREATE POLICY "tgt_types_write" ON target_types FOR ALL
USING ((SELECT check_permission((SELECT auth.uid()), 'settings.update'::text)));


-- +++ targets ───────────────────────────────────────────
DROP POLICY IF EXISTS "tgt_insert" ON targets;
CREATE POLICY "tgt_insert" ON targets FOR INSERT
WITH CHECK (((SELECT check_permission((SELECT auth.uid()), 'targets.read_all'::text)) OR (((SELECT check_permission((SELECT auth.uid()), 'targets.create'::text)) OR (SELECT check_permission((SELECT auth.uid()), 'targets.assign'::text))) AND ((((scope)::text = 'individual'::text) AND (scope_id IN ( SELECT hr_employees.id
   FROM hr_employees
  WHERE (hr_employees.branch_id = ( SELECT hr_employees_1.branch_id
           FROM hr_employees hr_employees_1
          WHERE (hr_employees_1.user_id = (SELECT auth.uid()))
         LIMIT 1))))) OR (((scope)::text = 'branch'::text) AND (scope_id = ( SELECT hr_employees.branch_id
   FROM hr_employees
  WHERE (hr_employees.user_id = (SELECT auth.uid()))
 LIMIT 1))) OR (((scope)::text = 'department'::text) AND (scope_id IN ( SELECT hr_departments.id
   FROM hr_departments
  WHERE (hr_departments.branch_id = ( SELECT hr_employees.branch_id
           FROM hr_employees
          WHERE (hr_employees.user_id = (SELECT auth.uid()))
         LIMIT 1)))))))));

DROP POLICY IF EXISTS "tgt_read" ON targets;
CREATE POLICY "tgt_read" ON targets FOR SELECT
USING (((((scope)::text = 'individual'::text) AND (scope_id IN ( SELECT hr_employees.id
   FROM hr_employees
  WHERE (hr_employees.user_id = (SELECT auth.uid()))))) OR ((SELECT check_permission((SELECT auth.uid()), 'targets.read_team'::text)) AND ((((scope)::text = 'branch'::text) AND (scope_id = ( SELECT hr_employees.branch_id
   FROM hr_employees
  WHERE (hr_employees.user_id = (SELECT auth.uid()))
 LIMIT 1))) OR (((scope)::text = 'individual'::text) AND (scope_id IN ( SELECT hr_employees.id
   FROM hr_employees
  WHERE (hr_employees.branch_id = ( SELECT hr_employees_1.branch_id
           FROM hr_employees hr_employees_1
          WHERE (hr_employees_1.user_id = (SELECT auth.uid()))
         LIMIT 1))))))) OR (SELECT check_permission((SELECT auth.uid()), 'targets.read_all'::text))));

DROP POLICY IF EXISTS "tgt_update" ON targets;
CREATE POLICY "tgt_update" ON targets FOR UPDATE
USING (((SELECT check_permission((SELECT auth.uid()), 'targets.read_all'::text)) OR (((SELECT check_permission((SELECT auth.uid()), 'targets.update'::text)) OR (SELECT check_permission((SELECT auth.uid()), 'targets.assign'::text))) AND ((((scope)::text = 'individual'::text) AND (scope_id IN ( SELECT hr_employees.id
   FROM hr_employees
  WHERE (hr_employees.branch_id = ( SELECT hr_employees_1.branch_id
           FROM hr_employees hr_employees_1
          WHERE (hr_employees_1.user_id = (SELECT auth.uid()))))))) OR (((scope)::text = 'branch'::text) AND (scope_id = ( SELECT hr_employees.branch_id
   FROM hr_employees
  WHERE (hr_employees.user_id = (SELECT auth.uid()))))) OR (((scope)::text = 'department'::text) AND (scope_id IN ( SELECT hr_departments.id
   FROM hr_departments
  WHERE (hr_departments.branch_id = ( SELECT hr_employees.branch_id
           FROM hr_employees
          WHERE (hr_employees.user_id = (SELECT auth.uid())))))))))))
WITH CHECK (((SELECT check_permission((SELECT auth.uid()), 'targets.read_all'::text)) OR (((SELECT check_permission((SELECT auth.uid()), 'targets.update'::text)) OR (SELECT check_permission((SELECT auth.uid()), 'targets.assign'::text))) AND ((((scope)::text = 'individual'::text) AND (scope_id IN ( SELECT hr_employees.id
   FROM hr_employees
  WHERE (hr_employees.branch_id = ( SELECT hr_employees_1.branch_id
           FROM hr_employees hr_employees_1
          WHERE (hr_employees_1.user_id = (SELECT auth.uid()))))))) OR (((scope)::text = 'branch'::text) AND (scope_id = ( SELECT hr_employees.branch_id
   FROM hr_employees
  WHERE (hr_employees.user_id = (SELECT auth.uid()))))) OR (((scope)::text = 'department'::text) AND (scope_id IN ( SELECT hr_departments.id
   FROM hr_departments
  WHERE (hr_departments.branch_id = ( SELECT hr_employees.branch_id
           FROM hr_employees
          WHERE (hr_employees.user_id = (SELECT auth.uid())))))))))));


-- +++ units ─────────────────────────────────────────────
DROP POLICY IF EXISTS "units_read" ON units;
CREATE POLICY "units_read" ON units FOR SELECT
USING (((SELECT auth.uid()) IS NOT NULL));

DROP POLICY IF EXISTS "units_write" ON units;
CREATE POLICY "units_write" ON units FOR ALL
USING ((SELECT check_permission((SELECT auth.uid()), 'products.create'::text)));


-- +++ user_permission_overrides ─────────────────────────
DROP POLICY IF EXISTS "overrides_select" ON user_permission_overrides;
CREATE POLICY "overrides_select" ON user_permission_overrides FOR SELECT
USING (((user_id = (SELECT auth.uid())) OR (SELECT check_permission((SELECT auth.uid()), 'auth.users.read'::text))));

DROP POLICY IF EXISTS "overrides_write" ON user_permission_overrides;
CREATE POLICY "overrides_write" ON user_permission_overrides FOR ALL
USING ((SELECT check_permission((SELECT auth.uid()), 'auth.users.update'::text)));


-- +++ user_roles ────────────────────────────────────────
DROP POLICY IF EXISTS "user_roles_delete" ON user_roles;
CREATE POLICY "user_roles_delete" ON user_roles FOR DELETE
USING ((SELECT check_permission((SELECT auth.uid()), 'auth.users.update'::text)));

DROP POLICY IF EXISTS "user_roles_insert" ON user_roles;
CREATE POLICY "user_roles_insert" ON user_roles FOR INSERT
WITH CHECK ((SELECT check_permission((SELECT auth.uid()), 'auth.users.update'::text)));

DROP POLICY IF EXISTS "user_roles_select" ON user_roles;
CREATE POLICY "user_roles_select" ON user_roles FOR SELECT
USING (((user_id = (SELECT auth.uid())) OR (SELECT check_permission((SELECT auth.uid()), 'auth.users.read'::text))));

DROP POLICY IF EXISTS "user_roles_update" ON user_roles;
CREATE POLICY "user_roles_update" ON user_roles FOR UPDATE
USING ((SELECT check_permission((SELECT auth.uid()), 'auth.users.update'::text)));


-- +++ vault_transactions ────────────────────────────────
DROP POLICY IF EXISTS "vault_txn_read" ON vault_transactions;
CREATE POLICY "vault_txn_read" ON vault_transactions FOR SELECT
USING (((SELECT check_permission((SELECT auth.uid()), 'finance.vaults.read_all'::text)) OR ((SELECT check_permission((SELECT auth.uid()), 'finance.vaults.read'::text)) AND (vault_id IN ( SELECT vaults.id
   FROM vaults
  WHERE (vaults.responsible_id = (SELECT auth.uid())))))));

DROP POLICY IF EXISTS "vault_txn_write" ON vault_transactions;
CREATE POLICY "vault_txn_write" ON vault_transactions FOR ALL
USING ((SELECT check_permission((SELECT auth.uid()), 'finance.vaults.transact'::text)));


-- +++ vaults ────────────────────────────────────────────
DROP POLICY IF EXISTS "vaults_insert" ON vaults;
CREATE POLICY "vaults_insert" ON vaults FOR INSERT
WITH CHECK ((SELECT check_permission((SELECT auth.uid()), 'finance.vaults.create'::text)));

DROP POLICY IF EXISTS "vaults_read" ON vaults;
CREATE POLICY "vaults_read" ON vaults FOR SELECT
USING (((SELECT check_permission((SELECT auth.uid()), 'finance.vaults.read_all'::text)) OR ((SELECT check_permission((SELECT auth.uid()), 'finance.vaults.read'::text)) AND (responsible_id = (SELECT auth.uid())))));

DROP POLICY IF EXISTS "vaults_update" ON vaults;
CREATE POLICY "vaults_update" ON vaults FOR UPDATE
USING ((SELECT check_permission((SELECT auth.uid()), 'finance.vaults.update'::text)));


-- +++ visit_checklist_questions ─────────────────────────
DROP POLICY IF EXISTS "checklist_questions_read" ON visit_checklist_questions;
CREATE POLICY "checklist_questions_read" ON visit_checklist_questions FOR SELECT
USING (((SELECT auth.uid()) IS NOT NULL));

DROP POLICY IF EXISTS "checklist_questions_write" ON visit_checklist_questions;
CREATE POLICY "checklist_questions_write" ON visit_checklist_questions FOR ALL
USING ((SELECT check_permission((SELECT auth.uid()), 'checklists.manage'::text)));


-- +++ visit_checklist_responses ─────────────────────────
DROP POLICY IF EXISTS "checklist_responses_insert" ON visit_checklist_responses;
CREATE POLICY "checklist_responses_insert" ON visit_checklist_responses FOR INSERT
WITH CHECK (((SELECT check_permission((SELECT auth.uid()), 'activities.update_own'::text)) OR (SELECT check_permission((SELECT auth.uid()), 'activities.read_team'::text)) OR (SELECT check_permission((SELECT auth.uid()), 'activities.read_all'::text))));

DROP POLICY IF EXISTS "checklist_responses_read" ON visit_checklist_responses;
CREATE POLICY "checklist_responses_read" ON visit_checklist_responses FOR SELECT
USING (((SELECT check_permission((SELECT auth.uid()), 'activities.read_all'::text)) OR (SELECT check_permission((SELECT auth.uid()), 'activities.read_team'::text)) OR ((SELECT check_permission((SELECT auth.uid()), 'activities.update_own'::text)) AND (activity_id IN ( SELECT activities.id
   FROM activities
  WHERE (activities.created_by = (SELECT auth.uid())))))));

DROP POLICY IF EXISTS "checklist_responses_update" ON visit_checklist_responses;
CREATE POLICY "checklist_responses_update" ON visit_checklist_responses FOR UPDATE
USING (((SELECT check_permission((SELECT auth.uid()), 'activities.update_own'::text)) AND (activity_id IN ( SELECT activities.id
   FROM activities
  WHERE (activities.created_by = (SELECT auth.uid()))))));


-- +++ visit_checklist_templates ─────────────────────────
DROP POLICY IF EXISTS "checklist_templates_read" ON visit_checklist_templates;
CREATE POLICY "checklist_templates_read" ON visit_checklist_templates FOR SELECT
USING (((SELECT auth.uid()) IS NOT NULL));

DROP POLICY IF EXISTS "checklist_templates_write" ON visit_checklist_templates;
CREATE POLICY "checklist_templates_write" ON visit_checklist_templates FOR ALL
USING ((SELECT check_permission((SELECT auth.uid()), 'checklists.manage'::text)));


-- +++ visit_plan_items ──────────────────────────────────
DROP POLICY IF EXISTS "vpi_delete" ON visit_plan_items;
CREATE POLICY "vpi_delete" ON visit_plan_items FOR DELETE
USING ((((SELECT check_permission((SELECT auth.uid()), 'visit_plans.create'::text)) AND (EXISTS ( SELECT 1
   FROM visit_plans vp
  WHERE ((vp.id = visit_plan_items.plan_id) AND (vp.employee_id IN ( SELECT hr_employees.id
           FROM hr_employees
          WHERE (hr_employees.user_id = (SELECT auth.uid())))))))) OR ((SELECT check_permission((SELECT auth.uid()), 'visit_plans.update'::text)) AND (EXISTS ( SELECT 1
   FROM visit_plans vp
  WHERE ((vp.id = visit_plan_items.plan_id) AND (vp.employee_id IN ( SELECT hr_employees.id
           FROM hr_employees
          WHERE (hr_employees.branch_id = ( SELECT hr_employees_1.branch_id
                   FROM hr_employees hr_employees_1
                  WHERE (hr_employees_1.user_id = (SELECT auth.uid()))
                 LIMIT 1)))))))) OR (SELECT check_permission((SELECT auth.uid()), 'visit_plans.read_all'::text))));

DROP POLICY IF EXISTS "vpi_insert" ON visit_plan_items;
CREATE POLICY "vpi_insert" ON visit_plan_items FOR INSERT
WITH CHECK ((((SELECT check_permission((SELECT auth.uid()), 'visit_plans.create'::text)) AND (EXISTS ( SELECT 1
   FROM visit_plans vp
  WHERE ((vp.id = visit_plan_items.plan_id) AND ((vp.employee_id IN ( SELECT hr_employees.id
           FROM hr_employees
          WHERE (hr_employees.user_id = (SELECT auth.uid())))) OR (SELECT check_permission((SELECT auth.uid()), 'visit_plans.read_team'::text))))))) OR ((SELECT check_permission((SELECT auth.uid()), 'visit_plans.update'::text)) AND (EXISTS ( SELECT 1
   FROM visit_plans vp
  WHERE ((vp.id = visit_plan_items.plan_id) AND (vp.employee_id IN ( SELECT hr_employees.id
           FROM hr_employees
          WHERE (hr_employees.branch_id = ( SELECT hr_employees_1.branch_id
                   FROM hr_employees hr_employees_1
                  WHERE (hr_employees_1.user_id = (SELECT auth.uid()))
                 LIMIT 1)))))))) OR (SELECT check_permission((SELECT auth.uid()), 'visit_plans.read_all'::text))));

DROP POLICY IF EXISTS "vpi_read" ON visit_plan_items;
CREATE POLICY "vpi_read" ON visit_plan_items FOR SELECT
USING ((EXISTS ( SELECT 1
   FROM visit_plans vp
  WHERE ((vp.id = visit_plan_items.plan_id) AND ((vp.employee_id IN ( SELECT hr_employees.id
           FROM hr_employees
          WHERE (hr_employees.user_id = (SELECT auth.uid())))) OR (SELECT check_permission((SELECT auth.uid()), 'visit_plans.read_all'::text)))))));

DROP POLICY IF EXISTS "vpi_update" ON visit_plan_items;
CREATE POLICY "vpi_update" ON visit_plan_items FOR UPDATE
USING ((((SELECT check_permission((SELECT auth.uid()), 'activities.create'::text)) AND (EXISTS ( SELECT 1
   FROM visit_plans vp
  WHERE ((vp.id = visit_plan_items.plan_id) AND (vp.employee_id IN ( SELECT hr_employees.id
           FROM hr_employees
          WHERE (hr_employees.user_id = (SELECT auth.uid())))))))) OR ((SELECT check_permission((SELECT auth.uid()), 'visit_plans.create'::text)) AND (EXISTS ( SELECT 1
   FROM visit_plans vp
  WHERE ((vp.id = visit_plan_items.plan_id) AND (vp.employee_id IN ( SELECT hr_employees.id
           FROM hr_employees
          WHERE (hr_employees.user_id = (SELECT auth.uid())))))))) OR ((SELECT check_permission((SELECT auth.uid()), 'visit_plans.update'::text)) AND (EXISTS ( SELECT 1
   FROM visit_plans vp
  WHERE ((vp.id = visit_plan_items.plan_id) AND (vp.employee_id IN ( SELECT hr_employees.id
           FROM hr_employees
          WHERE (hr_employees.branch_id = ( SELECT hr_employees_1.branch_id
                   FROM hr_employees hr_employees_1
                  WHERE (hr_employees_1.user_id = (SELECT auth.uid()))
                 LIMIT 1)))))))) OR ((SELECT check_permission((SELECT auth.uid()), 'visit_plans.confirm'::text)) AND (EXISTS ( SELECT 1
   FROM visit_plans vp
  WHERE ((vp.id = visit_plan_items.plan_id) AND (vp.employee_id IN ( SELECT hr_employees.id
           FROM hr_employees
          WHERE (hr_employees.branch_id = ( SELECT hr_employees_1.branch_id
                   FROM hr_employees hr_employees_1
                  WHERE (hr_employees_1.user_id = (SELECT auth.uid()))
                 LIMIT 1)))))))) OR (SELECT check_permission((SELECT auth.uid()), 'visit_plans.read_all'::text))));


-- +++ visit_plan_templates ──────────────────────────────
DROP POLICY IF EXISTS "vpt_insert" ON visit_plan_templates;
CREATE POLICY "vpt_insert" ON visit_plan_templates FOR INSERT
WITH CHECK (((SELECT check_permission((SELECT auth.uid()), 'visit_plans.create'::text)) AND ((branch_id IS NULL) OR (branch_id IN ( SELECT hr_employees.branch_id
   FROM hr_employees
  WHERE (hr_employees.user_id = (SELECT auth.uid())))) OR (SELECT check_permission((SELECT auth.uid()), 'visit_plans.read_all'::text)))));

DROP POLICY IF EXISTS "vpt_read" ON visit_plan_templates;
CREATE POLICY "vpt_read" ON visit_plan_templates FOR SELECT
USING (((SELECT auth.uid()) IS NOT NULL));

DROP POLICY IF EXISTS "vpt_update" ON visit_plan_templates;
CREATE POLICY "vpt_update" ON visit_plan_templates FOR UPDATE
USING ((((SELECT check_permission((SELECT auth.uid()), 'visit_plans.create'::text)) AND ((created_by = (SELECT auth.uid())) OR (employee_id IN ( SELECT hr_employees.id
   FROM hr_employees
  WHERE (hr_employees.branch_id = ( SELECT hr_employees_1.branch_id
           FROM hr_employees hr_employees_1
          WHERE (hr_employees_1.user_id = (SELECT auth.uid())))))) OR (branch_id IN ( SELECT hr_employees.branch_id
   FROM hr_employees
  WHERE (hr_employees.user_id = (SELECT auth.uid())))))) OR (SELECT check_permission((SELECT auth.uid()), 'visit_plans.read_all'::text))))
WITH CHECK ((((SELECT check_permission((SELECT auth.uid()), 'visit_plans.create'::text)) AND ((created_by = (SELECT auth.uid())) OR (employee_id IN ( SELECT hr_employees.id
   FROM hr_employees
  WHERE (hr_employees.branch_id = ( SELECT hr_employees_1.branch_id
           FROM hr_employees hr_employees_1
          WHERE (hr_employees_1.user_id = (SELECT auth.uid())))))) OR (branch_id IN ( SELECT hr_employees.branch_id
   FROM hr_employees
  WHERE (hr_employees.user_id = (SELECT auth.uid())))))) OR (SELECT check_permission((SELECT auth.uid()), 'visit_plans.read_all'::text))));

DROP POLICY IF EXISTS "vpt_write" ON visit_plan_templates;
CREATE POLICY "vpt_write" ON visit_plan_templates FOR ALL
USING ((SELECT check_permission((SELECT auth.uid()), 'visit_plans.create'::text)));


-- +++ visit_plans ───────────────────────────────────────
DROP POLICY IF EXISTS "vp_insert" ON visit_plans;
CREATE POLICY "vp_insert" ON visit_plans FOR INSERT
WITH CHECK (((SELECT check_permission((SELECT auth.uid()), 'visit_plans.create'::text)) AND ((employee_id IN ( SELECT hr_employees.id
   FROM hr_employees
  WHERE (hr_employees.user_id = (SELECT auth.uid())))) OR ((SELECT check_permission((SELECT auth.uid()), 'visit_plans.read_team'::text)) AND (employee_id IN ( SELECT hr_employees.id
   FROM hr_employees
  WHERE (hr_employees.branch_id = ( SELECT hr_employees_1.branch_id
           FROM hr_employees hr_employees_1
          WHERE (hr_employees_1.user_id = (SELECT auth.uid()))))))) OR (SELECT check_permission((SELECT auth.uid()), 'visit_plans.read_all'::text)))));

DROP POLICY IF EXISTS "vp_read" ON visit_plans;
CREATE POLICY "vp_read" ON visit_plans FOR SELECT
USING (((employee_id IN ( SELECT hr_employees.id
   FROM hr_employees
  WHERE (hr_employees.user_id = (SELECT auth.uid())))) OR ((SELECT check_permission((SELECT auth.uid()), 'visit_plans.read_team'::text)) AND (employee_id IN ( SELECT hr_employees.id
   FROM hr_employees
  WHERE (hr_employees.branch_id = ( SELECT hr_employees_1.branch_id
           FROM hr_employees hr_employees_1
          WHERE (hr_employees_1.user_id = (SELECT auth.uid()))
         LIMIT 1))))) OR (SELECT check_permission((SELECT auth.uid()), 'visit_plans.read_all'::text))));

DROP POLICY IF EXISTS "vp_update" ON visit_plans;
CREATE POLICY "vp_update" ON visit_plans FOR UPDATE
USING ((((SELECT check_permission((SELECT auth.uid()), 'visit_plans.create'::text)) AND (employee_id IN ( SELECT hr_employees.id
   FROM hr_employees
  WHERE (hr_employees.branch_id = ( SELECT hr_employees_1.branch_id
           FROM hr_employees hr_employees_1
          WHERE (hr_employees_1.user_id = (SELECT auth.uid()))))))) OR ((SELECT check_permission((SELECT auth.uid()), 'visit_plans.confirm'::text)) AND (employee_id IN ( SELECT hr_employees.id
   FROM hr_employees
  WHERE (hr_employees.branch_id = ( SELECT hr_employees_1.branch_id
           FROM hr_employees hr_employees_1
          WHERE (hr_employees_1.user_id = (SELECT auth.uid()))))))) OR ((SELECT check_permission((SELECT auth.uid()), 'visit_plans.cancel'::text)) AND (employee_id IN ( SELECT hr_employees.id
   FROM hr_employees
  WHERE (hr_employees.branch_id = ( SELECT hr_employees_1.branch_id
           FROM hr_employees hr_employees_1
          WHERE (hr_employees_1.user_id = (SELECT auth.uid()))))))) OR (SELECT check_permission((SELECT auth.uid()), 'visit_plans.read_all'::text))))
WITH CHECK ((((SELECT check_permission((SELECT auth.uid()), 'visit_plans.create'::text)) AND (employee_id IN ( SELECT hr_employees.id
   FROM hr_employees
  WHERE (hr_employees.branch_id = ( SELECT hr_employees_1.branch_id
           FROM hr_employees hr_employees_1
          WHERE (hr_employees_1.user_id = (SELECT auth.uid()))))))) OR ((SELECT check_permission((SELECT auth.uid()), 'visit_plans.confirm'::text)) AND (employee_id IN ( SELECT hr_employees.id
   FROM hr_employees
  WHERE (hr_employees.branch_id = ( SELECT hr_employees_1.branch_id
           FROM hr_employees hr_employees_1
          WHERE (hr_employees_1.user_id = (SELECT auth.uid()))))))) OR ((SELECT check_permission((SELECT auth.uid()), 'visit_plans.cancel'::text)) AND (employee_id IN ( SELECT hr_employees.id
   FROM hr_employees
  WHERE (hr_employees.branch_id = ( SELECT hr_employees_1.branch_id
           FROM hr_employees hr_employees_1
          WHERE (hr_employees_1.user_id = (SELECT auth.uid()))))))) OR (SELECT check_permission((SELECT auth.uid()), 'visit_plans.read_all'::text))));

DROP POLICY IF EXISTS "vp_write" ON visit_plans;
CREATE POLICY "vp_write" ON visit_plans FOR ALL
USING ((SELECT check_permission((SELECT auth.uid()), 'visit_plans.create'::text)));


-- +++ warehouse_managers ────────────────────────────────
DROP POLICY IF EXISTS "wh_managers_read" ON warehouse_managers;
CREATE POLICY "wh_managers_read" ON warehouse_managers FOR SELECT
USING (((SELECT check_permission((SELECT auth.uid()), 'inventory.read_all'::text)) OR ((SELECT check_permission((SELECT auth.uid()), 'inventory.read'::text)) AND (warehouse_id IN ( SELECT user_warehouse_ids_set() AS user_warehouse_ids_set)))));

DROP POLICY IF EXISTS "wh_managers_write" ON warehouse_managers;
CREATE POLICY "wh_managers_write" ON warehouse_managers FOR ALL
USING ((SELECT check_permission((SELECT auth.uid()), 'inventory.create'::text)));


-- +++ warehouses ────────────────────────────────────────
DROP POLICY IF EXISTS "warehouses_read" ON warehouses;
CREATE POLICY "warehouses_read" ON warehouses FOR SELECT
USING (((SELECT check_permission((SELECT auth.uid()), 'inventory.read_all'::text)) OR ((SELECT check_permission((SELECT auth.uid()), 'inventory.read'::text)) AND (id IN ( SELECT user_warehouse_ids_set() AS user_warehouse_ids_set)))));

DROP POLICY IF EXISTS "warehouses_write" ON warehouses;
CREATE POLICY "warehouses_write" ON warehouses FOR ALL
USING ((SELECT check_permission((SELECT auth.uid()), 'inventory.create'::text)));

COMMIT;
