import type { AiOpsConsoleSnapshot } from './types'

const PREVIEW_NOW = '2026-08-16T15:30:00.000Z'

export const AI_OPERATIONS_PREVIEW_DATA: AiOpsConsoleSnapshot = {
  mode: 'preview',
  integration_state: 'preview_only',
  generated_at: PREVIEW_NOW,
  data_as_of: '2026-08-16T15:00:00.000Z',
  settings: {
    planner_enabled: false,
    shadow_mode: true,
    auto_commit_enabled: false,
    max_cases_per_snapshot: 30,
    max_actions_per_run: 3,
    planner_policy_version: 'v1',
    tool_contract_version: 'v1',
    state_version: 1,
    updated_at: null,
  },
  trust: [
    { domain: 'sales', state: 'posting_consistency_only', as_of: '2026-08-16T15:00:00.000Z', note: 'الإيراد متسق مع قيود الترحيل، بدون اعتماد على صفوف خام.' },
    { domain: 'receivables', state: 'verified', as_of: '2026-08-16T15:00:00.000Z', note: 'أرصدة الذمم والتحصيلات متاحة كمصدر قرار.' },
    { domain: 'customer_risk', state: 'partial', as_of: '2026-08-16T15:00:00.000Z', note: 'يستخدم كسجل تاريخي/إشارة تغير، وليس كصورة Current-State كاملة لكل العملاء.' },
    { domain: 'profitability', state: 'posting_consistency_only', as_of: '2026-08-16T15:00:00.000Z', note: 'تستخدم كإشارة إدارية وليست حقيقة محاسبية نهائية.' },
  ],
  pulse: [
    { key: 'sales_gap', label: 'فجوة الهدف', value: '−18%', tone: 'warning', trend: 'down', hint: 'المعدل الحالي أقل من المسار المطلوب.' },
    { key: 'overdue_ar', label: 'مديونيات متأخرة', value: '86.4 ألف', tone: 'danger', trend: 'up', hint: 'الحالة المالية لا تحدد وحدها من يجب أن يتصرف.' },
    { key: 'reactivation', label: 'فرص إعادة التفعيل', value: '12', tone: 'good', trend: 'up', hint: 'مرشحين بقيمة تاريخية مرتفعة ولم يشتروا مؤخرًا.' },
    { key: 'work_collision', label: 'حالات لها Work قائم', value: '3', tone: 'neutral', trend: 'flat', hint: 'لن ينشئ Planner مهام مكررة لها.' },
  ],
  attention: [
    {
      id: 'preview-case-001',
      case_key: 'receivables:overdue_invoice:11111111-1111-4111-8111-111111111111',
      domain: 'receivables',
      case_type: 'overdue_invoice',
      entity_type: 'sales_order',
      entity_id: '11111111-1111-4111-8111-111111111111',
      entity_label: 'SO-DEMO-1842 · عميل ائتمان تجريبي',
      attention_class: 'exception',
      severity: 'high',
      status: 'monitored',
      title: 'فاتورة متأخرة لكن قرار الائتمان له مالك إداري واضح',
      reason: 'التأخير يستحق الانتباه، لكن سجل Credit Override وتعديل الاستحقاق والسياق الإداري أقوى من مجرد إسناد العميل لمندوب مبيعات.',
      first_seen_at: '2026-08-15T05:00:00.000Z',
      last_seen_at: PREVIEW_NOW,
      source_as_of: '2026-08-16T15:00:00.000Z',
      responsibility_label: 'صاحب قرار الاستثناء الائتماني',
      responsibility_basis: 'Credit override + governed due-date history + operational context، مع اعتبار المندوب كدليل مساند فقط',
      value_label: '20.6 ألف EGP',
      has_existing_work: false,
      linked_work_number: null,
      recommended_decision: 'MONITOR',
      review_after: '2026-08-22T06:00:00.000Z',
    },
    {
      id: 'preview-case-002',
      case_key: 'customer:reactivation:preview-002',
      domain: 'customers',
      case_type: 'high_value_reactivation',
      entity_type: 'customer',
      entity_id: '22222222-2222-4222-8222-222222222222',
      entity_label: 'عميل تجريبي · C-0314',
      attention_class: 'opportunity',
      severity: 'high',
      status: 'monitored',
      title: 'عميل تاريخي قوي خرج من نمط الشراء المعتاد',
      reason: 'انخفضت مبيعات آخر 90 يومًا بوضوح مقارنة بالفترة السابقة مع بقاء القيمة التاريخية مرتفعة.',
      first_seen_at: '2026-08-14T05:00:00.000Z',
      last_seen_at: PREVIEW_NOW,
      source_as_of: '2026-08-16T15:00:00.000Z',
      responsibility_label: 'المندوب الحالي للعميل',
      responsibility_basis: 'العلاقة الحالية مناسبة، لكن هناك Work قائمة بالفعل فلا يُنشأ عنصر جديد.',
      value_label: 'Tier A',
      has_existing_work: true,
      linked_work_number: 1042,
      recommended_decision: 'MONITOR',
      review_after: '2026-08-18T08:00:00.000Z',
    },
    {
      id: 'preview-case-003',
      case_key: 'work:continuity:preview-003',
      domain: 'work',
      case_type: 'blocked_high_priority',
      entity_type: null,
      entity_id: null,
      entity_label: 'Work #998',
      attention_class: 'continuity',
      severity: 'high',
      status: 'open',
      title: 'عمل أولوية عالية متوقف على اعتماد خارجي',
      reason: 'المهمة Waiting وموعد الإجراء التالي مضى؛ لا يلزم إنشاء مهمة جديدة، المطلوب تصعيد/متابعة الموجود.',
      first_seen_at: '2026-08-16T08:00:00.000Z',
      last_seen_at: PREVIEW_NOW,
      source_as_of: PREVIEW_NOW,
      responsibility_label: 'صاحب المهمة الحالي',
      responsibility_basis: 'Work accountability + waiting state',
      value_label: null,
      has_existing_work: true,
      linked_work_number: 998,
      recommended_decision: 'ESCALATE',
      review_after: null,
    },
  ],
  recent_runs: [
    {
      id: 'preview-run-001',
      run_key: 'daily-2026-08-16-am',
      run_type: 'daily_operations',
      business_date: '2026-08-16',
      scheduled_for: '2026-08-16T05:00:00.000Z',
      status: 'completed',
      checkpoint: 'decisions_staged',
      attempt_no: 1,
      cases_seen: 18,
      cases_investigated: 5,
      decisions_count: 5,
      work_created_count: 0,
      started_at: '2026-08-16T05:00:07.000Z',
      completed_at: '2026-08-16T05:01:12.000Z',
      error_class: null,
      error_message: null,
    },
    {
      id: 'preview-run-002',
      run_key: 'daily-2026-08-15-pm',
      run_type: 'daily_operations',
      business_date: '2026-08-15',
      scheduled_for: '2026-08-15T14:00:00.000Z',
      status: 'partial',
      checkpoint: 'decisions_staged',
      attempt_no: 2,
      cases_seen: 21,
      cases_investigated: 6,
      decisions_count: 4,
      work_created_count: 0,
      started_at: '2026-08-15T14:00:05.000Z',
      completed_at: '2026-08-15T14:03:41.000Z',
      error_class: 'drilldown_unavailable',
      error_message: 'تعذر استكمال دليل حالة واحدة؛ تم حفظ باقي القرارات بدون فقد.',
    },
  ],
  context: [
    {
      id: 'preview-context-001',
      subject_type: 'customer',
      subject_id: '55555555-5555-4555-8555-555555555555',
      subject_label: 'عميل ائتمان تجريبي',
      context_type: 'temporary_collection_arrangement',
      summary: 'تم الاتفاق إداريًا على مهلة تحصيل مؤقتة؛ لا تُصعّد المديونية قبل تاريخ المراجعة.',
      owner_label: 'صاحب قرار الاستثناء الائتماني',
      source_type: 'human',
      confidence_class: 'approved_human',
      lifecycle_type: 'review_on',
      valid_until: null,
      review_on: '2026-08-22',
      status: 'active',
    },
    {
      id: 'preview-context-002',
      subject_type: 'employee',
      subject_id: '44444444-4444-4444-8444-444444444444',
      subject_label: 'مثال مسؤولية مؤقتة',
      context_type: 'temporary_coverage',
      summary: 'يتولى تغطية منطقة زميله مؤقتًا خلال فترة محددة؛ يستخدم فقط لترجيح التوجيه وليس كتغيير تنظيمي دائم.',
      owner_label: 'المدير الإداري',
      source_type: 'human',
      confidence_class: 'explicit_human',
      lifecycle_type: 'valid_until',
      valid_until: '2026-08-20T20:59:59.000Z',
      review_on: null,
      status: 'active',
    },
  ],
}
