import type { AiOpsCaseDetail } from './types'

export const AI_OPERATIONS_PREVIEW_CASE_DETAILS: Record<string, AiOpsCaseDetail> = {
  'preview-case-001': {
    case_id: 'preview-case-001',
    case_key: 'receivables:overdue_invoice:11111111-1111-4111-8111-111111111111',
    business_date: '2026-08-16',
    facts: [
      { label: 'الرصيد المتبقي', value: '20.6 ألف EGP' },
      { label: 'أيام التأخير', value: '34 يومًا' },
      { label: 'حالة الفاتورة', value: 'Delivered / Credit' },
      { label: 'آخر تعديل للاستحقاق', value: 'قبل 12 يومًا' },
    ],
    responsibility_evidence: [
      {
        evidence_type: 'explicit_credit_override',
        label: 'صاحب قرار تجاوز الائتمان',
        user_id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',
        user_label: 'مسؤول إداري تجريبي',
        strength: 'direct',
        active_work_actor: true,
        occurred_at: '2026-07-12T09:20:00.000Z',
        note: 'دليل مباشر على ملكية قرار الاستثناء الائتماني؛ لا يعني وحده وجوب إنشاء مهمة.',
      },
      {
        evidence_type: 'governed_due_date_change',
        label: 'آخر من عدّل تاريخ الاستحقاق',
        user_id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',
        user_label: 'مسؤول إداري تجريبي',
        strength: 'direct',
        active_work_actor: true,
        occurred_at: '2026-08-04T10:15:00.000Z',
        note: 'التعديل موثق بسبب إداري؛ لذلك يجب مراجعة صاحب القرار قبل توجيه التحصيل لهيكل المبيعات.',
      },
      {
        evidence_type: 'current_customer_assignment',
        label: 'مندوب العميل الحالي',
        user_id: 'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',
        user_label: 'مندوب مبيعات تجريبي',
        strength: 'supporting',
        active_work_actor: true,
        occurred_at: null,
        note: 'علاقة تشغيل حالية بالعميل، لكنها أضعف من دليل ملكية قرار الائتمان في هذه الحالة.',
      },
      {
        evidence_type: 'order_rep',
        label: 'مندوب الفاتورة',
        user_id: 'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',
        user_label: 'مندوب مبيعات تجريبي',
        strength: 'supporting',
        active_work_actor: true,
        occurred_at: null,
        note: 'دليل علاقة بالمعاملة وليس إثبات مسؤولية عن قرار فتح الائتمان.',
      },
      {
        evidence_type: 'order_creator_not_necessarily_accountable',
        label: 'منشئ الفاتورة',
        user_id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',
        user_label: 'مسؤول إداري تجريبي',
        strength: 'contextual',
        active_work_actor: true,
        occurred_at: '2026-07-12T09:00:00.000Z',
        note: 'يُعرض كسياق فقط؛ الإنشاء وحده لا يساوي المسؤولية.',
      },
    ],
    existing_work: [],
    relevant_context_ids: ['preview-context-001'],
    decision_review: {
      decision_type: 'MONITOR',
      concise_rationale: 'الحالة متأخرة ماليًا، لكن يوجد دليل مباشر أن الاستحقاق والائتمان تحت قرار إداري خاص، مع سياق بشري نشط يحدد موعد مراجعة. إنشاء مهمة للمندوب الآن سيكون توجيهًا جامدًا وغير صحيح.',
      why_this_owner: 'المتابعة الإدارية ترجع لصاحب قرار الاستثناء الائتماني، وليس تلقائيًا لمندوب العميل أو مشرف المبيعات.',
      why_now: 'لا يوجد إجراء تنفيذي مطلوب قبل تاريخ المراجعة المثبت في السياق التشغيلي.',
      confidence: 0.94,
      requires_human_review: false,
    },
  },
  'preview-case-002': {
    case_id: 'preview-case-002',
    case_key: 'customer:reactivation:preview-002',
    business_date: '2026-08-16',
    facts: [
      { label: 'القيمة التاريخية', value: 'Tier A' },
      { label: 'التغير', value: 'هبوط واضح في آخر 90 يومًا' },
      { label: 'Work قائم', value: '#1042' },
    ],
    responsibility_evidence: [
      {
        evidence_type: 'current_customer_assignment',
        label: 'المندوب الحالي',
        user_id: 'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',
        user_label: 'مندوب مبيعات تجريبي',
        strength: 'direct',
        active_work_actor: true,
        occurred_at: null,
        note: 'العلاقة التشغيلية الحالية مناسبة للمتابعة، لكن لا حاجة لمهمة جديدة لأن Work موجودة بالفعل.',
      },
    ],
    existing_work: [
      {
        work_item_id: 'cccccccc-cccc-4ccc-8ccc-cccccccccccc',
        work_number: 1042,
        status: 'in_progress',
        relation_type: 'relates_to',
        title: 'إعادة تنشيط العميل التجريبي',
      },
    ],
    relevant_context_ids: [],
    decision_review: {
      decision_type: 'MONITOR',
      concise_rationale: 'الفرصة قائمة لكن لها Work نشطة بالفعل؛ إنشاء عنصر جديد سيخلق ازدواجية وتشتيتًا.',
      why_this_owner: 'المندوب الحالي هو منفذ المتابعة القائمة بالفعل.',
      why_now: 'المطلوب متابعة نتيجة Work الحالية بدل إنشاء إجراء موازٍ.',
      confidence: 0.91,
      requires_human_review: false,
    },
  },
  'preview-case-003': {
    case_id: 'preview-case-003',
    case_key: 'work:continuity:preview-003',
    business_date: '2026-08-16',
    facts: [
      { label: 'حالة Work', value: 'Waiting' },
      { label: 'موعد الإجراء التالي', value: 'مضى بالفعل' },
      { label: 'الأولوية', value: 'High' },
    ],
    responsibility_evidence: [
      {
        evidence_type: 'existing_work_accountability',
        label: 'صاحب Work الحالي',
        user_id: 'dddddddd-dddd-4ddd-8ddd-dddddddddddd',
        user_label: 'مسؤول تجريبي',
        strength: 'direct',
        active_work_actor: true,
        occurred_at: null,
        note: 'المسؤولية موجودة أصلًا في Work Engine؛ لا نعيد حلها من الهيكل التنظيمي.',
      },
    ],
    existing_work: [
      {
        work_item_id: 'dddddddd-dddd-4ddd-8ddd-eeeeeeeeeeee',
        work_number: 998,
        status: 'waiting',
        relation_type: 'primary',
        title: 'عمل تجريبي متوقف على اعتماد خارجي',
      },
    ],
    relevant_context_ids: [],
    decision_review: {
      decision_type: 'ESCALATE',
      concise_rationale: 'المشكلة ليست نقص مهمة؛ المشكلة أن Work قائمة تجاوزت موعد المتابعة وهي في Waiting.',
      why_this_owner: 'التصعيد يحافظ على accountable owner الحالي بدل اختراع مالك جديد.',
      why_now: 'next_action_at أصبح مستحقًا بدون تقدم.',
      confidence: 0.96,
      requires_human_review: false,
    },
  },
}
